### ISSUE TITLE
Update quickstart page to account for new k3d versions

### ISSUE THREAD

**Issue by mowies** [keptn/keptn.github.io#1002]
The quickstart page still uses k3d with version `4.4.4` which was released on 19 May 2021.
The latest stable k3d version is `5.2.2` which has lots of new feature and also changed the CLI arguments in a breaking way.
So users who already have k3d and want to install keptn with the command from the quickstart page here will get errors from k3d.

**Comment by agardnerIT** [comment]
docs now use `5.3.0` which is old now, but not as old as `4.4.4`! Can we close this?

**Comment by mowies** [comment]
let's close this
