### ISSUE TITLE
Document missing Keptn APIs such as statistics

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn.github.io#1003]
Looking at the current documentation on the Keptn API I see that there are several API updates missing
Here is the link to the current Keptn 0.11.x docuemtnation for the API: https://keptn.sh/docs/0.11.x/reference/api/#explore-the-keptn-api

Whats missing is for instance a reference to the secrets or statistics api

**Comment by oleg-nenashev** [comment]
References:

* Secret Service: https://github.com/keptn/keptn/tree/master/secret-service  . Includes guides for Swagger docs
* Statistics service with documentation in README: https://github.com/keptn/keptn/tree/master/statistics-service

Later we will need to deduplicate the content
