### ISSUE TITLE
Broken "read docs" link on front page

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn.github.io#1039]
The link "Read docs" points to https://keptn.sh/docs/0.7.x/monitoring/.
The link should actually point to the Keptn documentation https://keptn.sh/docs/ or even to the latest version e.g. https://keptn.sh/docs/0.12.x/
![image (9)](https://user-images.githubusercontent.com/10980861/153878246-a3c3f1cf-7e11-4bac-aa55-bd2dfd441d2d.png)

**Comment by oleg-nenashev** [comment]
Duplicates https://github.com/keptn/keptn.github.io/issues/991

**Comment by StackScribe** [comment]
This can be closed.  The link now points to keptn.sh/docs and is working correctly.
