### ISSUE TITLE
Check and fix xrefs in "Architecture" document

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1043]
The https://keptn.sh/docs/concepts/architecture/ document includes links to many other sections in the documentation for information about various components.  Many/most of these seem to reference the 0.8.x docs which are no longer built as part of the doc set so yield a 404.

Issue identified for Release 0.12.x docs but I suspect the fix also needs to be applied to 0.11.x, 0.10.0, and 0.9.2.

**Comment by DavidPHirsch** [comment]
outdated
