### ISSUE TITLE
Create "Concepts" article about events

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1044]
The following information was gleaned from responses to a Slack query.  The material needs technical review.  Not sure if the information should be left at this level or expanded into a guide that gives instructions and examples for each implementation option.

=============================================================

Keptn event modeling can be used to provide a common service (such as a security scan)  across multiple applications that provide CloudEvents.  This includes DockerHub, GoogleCloudRegistry, and Artifactory "push" events.  Keptn can handle a virtually unlimited number of events.

Implementation options include:
* Expose the data to a monitoring system such as Prometheus or Dynatrace then create an SLI provider that queries this data
* Use the [Keptn send event](https://keptn.sh/docs/0.10.x/reference/cli/commands/keptn_send_event/) command to integrate any event that comes through CloudEvents with Keptn.  A REST API is also available for this.
* Use the [keptn.groovy](https://github.com/keptn-sandbox/keptn-jenkins-library/blob/master/src/sh/keptn/Keptn.groovy)  Jenkins library that sends events to Keptn to trigger sequences.  For example, use a Jenkins Pipeline to build a container and then trigger a Keptn Sequence to deploy, test, and evaluate that container for functionality, performance, and security.

**Comment by StackScribe** [comment]
Afzal responded to another Slack question with more information:

In keptn API , Event is a part of api GET & POST request, which retrieves the latest event & drives the received event.
ref: https://keptn.sh/docs/0.10.x/reference/api/

[Afzal](https://app.slack.com/team/U031TMH62TX)  [2 days ago](https://keptn.slack.com/archives/CNRCGFU3U/p1645201508741889?thread_ts=1645199549.147359&cid=CNRCGFU3U)
e.g.
apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "deployment"
        - name: "release"

    - name: "hardening"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "dev.delivery.finished"
        tasks: 
        - name: "deployment"
        - name: "release"

    - name: "production"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "hardening.delivery.finished"
        tasks: 
        - name: "deployment"
        - name: "release"
An array of events that trigger the sequence is declared on triggeredOn
ref :https://keptn.sh/docs/0.10.x/manage/shipyard/

----------------------------------------------------------------
The Keptn specification also has a great section about this: https://github.com/keptn/spec/blob/master/cloudevents.md#type
-----------------------------------------------------------------

**Comment by DavidPHirsch** [comment]
stale
