### ISSUE TITLE
Create "Events" article in "Concepts"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1045]
The "Concepts" section should include an article about "Events"

@agrimmer provides the following notes for a start:

In a nutshell:
* Keptn orchestrates sequences of tasks.
* For every Task Keptn sends a .triggered event, e.g: deployment.triggered, test.triggered, evaluation.triggered
The Event Payload contains contextual information about the Keptn Project, Service, Stage as well as additional information that is specific for that task, e.g: which test should be executed or which image should be deployed
* Keptn Services can “subscribe” to Events to “take action” when the Keptn Service is able to fulfill a task. A Keptn Service indicates to Keptn that it takes a task by initially sending a .started and a .finished event when the task execution is done.
* Keptn Services can also “subscript” to Events without sending a .started and .finished -> an example here are notification services e.g: sending information to a slack channel

Andi's office hours from the latest KubeCon – here is the link -> [https://www.youtube.com/watch?v=WVRdF0ZvApw](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWVRdF0ZvApw&data=04%7C01%7Cmeg.mcroberts%40dynatrace.com%7C54e08cc57d5f4188bed708d9ef8cae5d%7C70ebe3a35b30435d9d677716d74ca190%7C1%7C0%7C637804209855017328%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uGsZTui8%2FcSOvhthtj3hg7ul4%2FpxCXtWV8EBNVQ%2ByxI%3D&reserved=0) is also useful.   It explains the separation of concerns between process and tooling and explains how Keptn uses events to integrate with the individual point tools.  Perhaps itheshould be linked or embedded in the article.

**Comment by DavidPHirsch** [comment]
stale
