### ISSUE TITLE
Create styleguide for the website

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#1050]
It would be nice to have guidelines how to contribute content, e.g. line breaks and formatting.

**Comment by iamrajiv** [comment]
@oleg-nenashev Instead of writing our own guidelines we can follow this [https://github.com/github/docs/blob/main/contributing/content-style-guide.md](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) or any other standard guidelines.

**Comment by DavidPHirsch** [comment]
stale
