### ISSUE TITLE
Explore using Gitpod as a valid development for contributions to keptn

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1061]
https://www.gitpod.io/

Gitpod seems to be a nice tool that can lower the barriers for contribution, especially for junior people running Windows on small computers, perhaps with slow internet connections.

**Comment by StackScribe** [comment]
Has someone gotten us set up with Gitpod and confirmed that it works?  I think that needs to happen before we are ready to document how to use it.  It does not look like keptn is pre-qualified so I think we need to apply -- I really don't know much about how to do this but information is available at https://www.gitpod.io/blog/gitpod-for-opensource .

I know that some Jenkins people have been experimenting with it.  Some of the She Codes Africa participants tried it out and really liked it.  Most of them run Windows computers so it really nice if they can avoid the complexities of setting up a development environment!

What I don't know is if Gitpod can be used for Keptn demos.  Whoever wants to explore this can tell us  what the appropriate uses are for it.

**Comment by DavidPHirsch** [comment]
stale
