### ISSUE TITLE
discuss use of GitHub CLI in CONTRIBUTING.md

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1063]
Some of these bits could be simplified via GitHub CLI: https://cli.github.com/
Maybe it is something to recommend for newcomer contributors in the next iteration of the guidelines

_Originally posted by @oleg-nenashev in https://github.com/keptn/keptn.github.io/pull/1060#r810540440_

**Comment by DavidPHirsch** [comment]
stale
