### ISSUE TITLE
add info about issues templates to CONTRIBUTING.md

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1064]
NIT: Ideally should be handled by issues templates. There is a support for forms introduced recently, can show it to you next week. E.g. see https://github.com/jenkins-infra/helpdesk/tree/main/.github/ISSUE_TEMPLATE by @lemeurherve

_Originally posted by @oleg-nenashev in https://github.com/keptn/keptn.github.io/pull/1060#r810540138_

**Comment by DavidPHirsch** [comment]
stale
