### ISSUE TITLE
Update docs: must use V5 of K3d

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1065]
From Christian Kreuzberger on Slack:
I have made a quick fix for README to also use version 5 of K3d. Tested it locally, seems to work fine. [https://github.com/keptn/keptn/pull/6](https://github.com/keptn/keptn/pull/6926)

Need to scrub through all documentation to find all places where this needs to be reflected

**Comment by Omkar0114** [comment]
Hey @StackScribe, 
I would like to work on this issue! Can you assign it to me?

**Comment by aepfli** [comment]
I am really sorry that we did not progress fast enough on this ticket and your pull request. Sadly the quickstart got removed in the meantime :(
