### ISSUE TITLE
Document using DCO in the contributing guide

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#1071]
Currently it is not trivial to use DCO, especially when editing from the web browser

Spin off of https://github.com/keptn/keptn.github.io/pull/1060 . See the comments from @mowies and @StackScribe

**Comment by AnonymousCodes911** [comment]
Hey @oleg-nenashev, I would like to work on this. I would really appreciate if @StackScribe can brief me on how to fix the DCO as I tried the last time and I wasn't able to get through. 
Thankyou!
