### ISSUE TITLE
Move Bridge documentation out of "Reference" section

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1086]
Bridge documentation is included in four files located in the Reference section of the documentation although they are not really structured as reference documentation.  These should be removed from the Reference section and instead be organized in a "Bridge" section under "Manage Keptn Project/Service".

We should also add a "Bridge" entry to the glossary and perhaps have a small "Concepts" article about the Bridge.

**Comment by Ciggzy1312** [comment]
I am working on it

**Comment by StackScribe** [comment]
This has been done
