### ISSUE TITLE
Create "Files" subsection in Reference section

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1087]
We should have good reference pages for all files that users manipulate.  For more information see https://docs.google.com/document/d/1rmSGUFsnYuNc_BGHGmkW-9iB3hrOYbMeA-mJmMOjGRk/edit# 

As a first phase, move existing files to a "Files" subsection in the "Reference" section:
* https://keptn.sh/docs/0.13.x/quality_gates/sli/ 
* https://keptn.sh/docs/0.13.x/quality_gates/sli-provider/
* https://keptn.sh/docs/0.13.x/quality_gates/slo/

This will give us the following structure for the Reference section:

   Reference
      - Keptn CLI
      - Keptn API
      - Files
          - sli
          - sli provider
          - slo
          - ...
      - Miscellany 

We should eventually restructure these pages to look like reference pages but just assembling them in one place is a good first step.

See https://docs.google.com/document/d/1rmSGUFsnYuNc_BGHGmkW-9iB3hrOYbMeA-mJmMOjGRk/edit?usp=sharing  for information about the strategy.

**Comment by Ciggzy1312** [comment]
@StackScribe I can give this a try

**Comment by StackScribe** [comment]
This has been done
