### ISSUE TITLE
Create "Github for Keptn contributors" doc in community repo

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1089]
The CONTRIBUTING.md files for the keptn/keptn and keptn.github.io repos each contain some basic information about working with GitHub.  This information should be merged into a single document in the community repo that can be referenced by the CONTRIBUTING.md files in all other repos.

**Comment by Ciggzy1312** [comment]
I am working on it

**Comment by oleg-nenashev** [comment]
@Ciggzy1312 Hi! What is the status of it? Are you still looking into it?

**Comment by Ciggzy1312** [comment]
@oleg-nenashev Hey, I think we should wait till the next community meeting on July 20 as there is a topic of discussion on restructuring the documentation
What do you say?

**Comment by DavidPHirsch** [comment]
stale
