### ISSUE TITLE
Create reference page for values.yaml

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1092]
Source material: https://github.com/keptn/keptn/blob/master/helm-service/chart/values.yaml#L10 

https://app.slack.com/client/TFHDUSPB7/threads/thread/C017T4KUAG3-1646834076.629209 .  Specifically:
 the values.yaml for keptn services - such as the helm-service typically allows you to define the values for the Distributor which is subscribing the keptn service with keptn's control plane. The STAGE_FILTER, PROJECT_FILTER and SERVICE_FILTER are all described in the distributor documentation where it says either "" (=all) or comma separated list -> https://github.com/keptn/keptn/blob/master/distributor/README.md

**Comment by StackScribe** [comment]
Please assign to @StackScribe

**Comment by DavidPHirsch** [comment]
connected PRs are closed
