### ISSUE TITLE
Add limitation for converting Data explorer tile into an SLI

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1105]
[Henrik Rexed](https://app.slack.com/team/U01UB286K8F) [Yesterday at 4:18 AM](https://keptn.slack.com/archives/CNRCGFU3U/p1647256728030579)
Hi I'm preparing a demo for an event where i'm using Keptn for the quality gate with the dynatrace service. I have built a dashboard with the right naming ( keptn is attaching the link to the dashboard in the keptn bridge) , but i has issues to get the metrics : no evaluation performed by lighthouse because SLI failed with message Data Explorer tile could not be converted to a metric query: Metric query generation requires that data explorer query has a metric.
i have several metrics in this dashboad, what is the rule to make it work?

1 reply

[Arthur Pitman](https://app.slack.com/team/U023C6Y0W8K)  [21 hours ago](https://keptn.slack.com/archives/CNRCGFU3U/p1647257941555359?thread_ts=1647256728.030579&cid=CNRCGFU3U)
Hi! Currently for the dynatrace-service to convert a Data explorer tile into an SLI, it must be specified using the Build tab of the Data explorer. Metrics using the Code tab are currently not supported.

**Comment by DavidPHirsch** [comment]
stale
