### ISSUE TITLE
Ask an expert links are broken

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#1106]
The calendly "get in touch" link on [this page](https://keptn.sh/why-keptn/) and on https://keptn.sh/community/#ask-an-expert still points to [@Jürgen Etzlstorfer](https://keptn.slack.com/team/UG51FTJ8Y)'s link.

**Comment by jetzlstorfer** [comment]
Could not verify that there are still references to my profile or contact information.
Closing this. FYI @oleg-nenashev
