### ISSUE TITLE
Fix "backup" vs "back up" in Backup & Restore page

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1108]
Edit https://keptn.sh/docs/0.13.x/operate/backup_and_restore/ to correct use of
"backup" (noun or adjective) versus "back up" (verb)

**Comment by subhamgcon** [comment]
Hey @StackScribe, Can I work on this issue?

**Comment by mehabhalodiya** [comment]
@StackScribe We can close this issue as it got resolved 🙂
