### ISSUE TITLE
[DOCS] Wording Update for Quick Start

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1109]
The quickstart docs say:

```
Now try the Multi-Stage Delivery example and / or Auto-Remediation examples (see below)
```

Whereas the auto-remediation will not work without first executing the multi-stage delivery example, so wording needs to be updated in both places on this page to that effect.

I can't add a label but this would be a good first issue.

**Comment by mehabhalodiya** [comment]
@johannes-b So I just need to update the above statement at https://github.com/keptn/keptn.github.io/blob/master/content/docs/quickstart/_index.md

And I would like to reform the above sentence as:
`First, execute the multi-stage delivery example and then try Auto-Remediation one`.
Also, we can provide a `NOTE:  Auto-Remediation will not work without first executing the Multi-Stage Delivery example.`

Please correct me, if I am wrong. Thanks!

**Comment by agardnerIT** [comment]
Closing as stale
