### ISSUE TITLE
Missing advanced install options for helm values

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#1112]
In Keptn 0.10, we had this page https://keptn.sh/docs/0.10.x/operate/advanced_install_options/ which contained helm values:

![image](https://user-images.githubusercontent.com/56065213/158562435-2be35dc2-133d-4895-b901-715ce2a5c1d2.png)

However, with Keptn 0.11 this was removed, and replaced with a link:

https://keptn.sh/docs/0.13.x/operate/advanced_install_options/

![image](https://user-images.githubusercontent.com/56065213/158562505-12e08894-e31d-446d-8724-1029c1f44a99.png)

This link leads to https://github.com/keptn/keptn/tree/0.13.1/installer/manifests/keptn which does not show any more valuable information.

FYI @thisthat @mowies @oleg-nenashev @agardnerIT @StackScribe

**Comment by thisthat** [comment]
Since keeping the table up2date was close to impossible (and personally I don't like to replicate information), we decided that it is best to redirect the users towards our helm charts so that they can check by themselves the possible configuration values.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks @thisthat . Do you believe that this is sufficient information for a user to customize Keptn?
![image](https://user-images.githubusercontent.com/56065213/158572978-5f9b3912-4ac8-4e2b-8e71-a1b139c70f9c.png)

![image](https://user-images.githubusercontent.com/56065213/158573003-e05fc742-5d75-430b-b562-8601a691f238.png)

**Comment by mowies** [comment]
To add some more options here, I would suggest adding back some of the info from the docs page but adding it into the helm chart directly as comments (especially in the `values.yml` file) so that it's easier to maintain. And then, it probably makes sense to add links to all the different values files that we have to the docs page.

**Comment by StackScribe** [comment]
See https://github.com/keptn/keptn/issues/7569 also

**Comment by DavidPHirsch** [comment]
stale
