### ISSUE TITLE
Improve API reference

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1113]
https://keptn.sh/docs/0.13.x/reference/api/ references http://YOUR.DOMAIN/api to see the API documentation.  That shows as a link which is, of course, broken in the documentation.  I would like to be able to view the complete documentation for the API as part of the documentation.

This PR is to investigate the issue.  Ideally, we should be able to autogenerate this documentation with some authored text that is embedded in the source code.

**Comment by DavidPHirsch** [comment]
stale
