### ISSUE TITLE
Review and refine Keptn CLI documentation

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1114]
Keptn CLI documentation is autogenerated by https://github.com/keptn/keptn.github.io/blob/master/.github/workflows/auto-update.yml .  This issue is to review and refine what is produced.

Specific notes for your consideration:
* Pages begin with a "Description" section that is instead named with the command name.  The "Synopsis" section then duplicates that text
* Commands should show "Syntax" rather than Synopsis
* The "Syntax" should show the actual calling sequence 
* Add "Usage" section with more details about how and when to use this command
* Add "Differences between versions" section to track history and preserve appropriate information about previous releases

**Comment by DavidPHirsch** [comment]
stale
