### ISSUE TITLE
Create reference page for Keptn Cloud Events

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1115]
We need a reference page in Reference/Miscellaneous that lists all Keptn Cloud Events.

Currently, https://github.com/keptn/keptn/blob/master/.github/workflows/auto-update-keptn-spec.yml generates this information into keptn/spec .  This needs to be in the documentation, preferably autogenerated but with the ability to include authored content about each event, including Differences between versions information.

The documentation should include all events for  core and all services, identified by service.  For bonus points, it would be nice to enable customers to run a command that provides them with a version of this documentation that reflects only the services installed in their Keptn environment.

**Comment by DavidPHirsch** [comment]
connected PR is merged
