### ISSUE TITLE
Integrate Lighthouse CI

### ISSUE THREAD

**Issue by iamrajiv** [keptn/keptn.github.io#1117]
## Description

Lighthouse is an open-source, automated tool for improving the quality of web pages. You can run it against any web page, public or requiring authentication. It has audits for performance, accessibility, progressive web apps, SEO, and more.

[Lighthouse](https://github.com/GoogleChrome/lighthouse) CI is a suite of tools that make continuously running, saving, retrieving, and asserting against Lighthouse results as easy as possible.

<img width="1059" alt="Screenshot 2022-03-17 at 2 46 56 PM" src="https://user-images.githubusercontent.com/42106787/158777185-12a437b1-e62d-448a-874d-34baaae20fcc.png">

Reference: https://github.com/GoogleChrome/lighthouse-ci

**Comment by iamrajiv** [comment]
@oleg-nenashev Can I work on this?

**Comment by iamrajiv** [comment]
@christian-kreuzberger-dtx I have updated the description.

**Comment by oleg-nenashev** [comment]
I am definitely interested in having this reporting for the website. Not 100% sure about having it as a part of the CI flow, but I see no problem with trying it out

**Comment by DavidPHirsch** [comment]
stale
