### ISSUE TITLE
Add K3d installation instructions

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1121]
https://keptn.sh/docs/0.13.x/operate/install/ and  has instructions for creating a K3s cluster but does not have instructions for a K3d cluster.

Excellent source material in https://www.youtube.com/watch?v=zVFLxaa2xkw .  Recommend writing up the information from this video and including a link to the video in that section.

**Comment by subhamgcon** [comment]
Can I work on this issue?

**Comment by DavidPHirsch** [comment]
stale
