### ISSUE TITLE
Define how to handle the new Docker terms when installing Docker

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1123]
Docs and videos link to https://docs.docker.com/engine/install/ for Docker installation.  That page now use the name Docker Desktop for <operating system>.  It also explains that they have  a new subscription policy -- basically that organizations over a certain size (expressed in # of employees or revenue) 

I was able to install it then got a pop-up explaining the new subscription policy.  I had to click "I accept" to proceed and it looks like it is installed -- at least docker --version and docker version work.

This issue is just to define how we should handle this in our docs and videos.  Separate issues should be filed to implement this.

**Comment by DavidPHirsch** [comment]
outdated
