### ISSUE TITLE
Add k0s installation instructions

### ISSUE THREAD

**Issue by Aju100** [keptn/keptn.github.io#1127]
![k3s](https://user-images.githubusercontent.com/29862610/159054446-32dc9fea-d4f1-41b5-a3cf-644b9ca8d5ce.png)
I would like to add here k0s installation instructions

**Comment by StackScribe** [comment]
Sounds good to me!  Be sure to include a brief description of what k0s is and its pros/cons -- not all of the existing options include this information but they should.

**Comment by Aju100** [comment]
sure great working on this

**Comment by DavidPHirsch** [comment]
stale
