### ISSUE TITLE
Correct information in Argo tile on "Integrations" page

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1146]
The Argo tile on the main "Integrations" page (https://keptn.sh/docs/integrations/) incorrectly states that this is for Argo CD.  The actual Argo page (https://keptn.sh/docs/integrations/) correctly says that this is for Argo Rollouts.

The  Argo page itself should be reviewed and possibly updated.  For example, it includes a compatibility table that goes up to Keptn 0.10.x and it links to and discusses a sample project whose README lists Keptn releases up to 0.8.0.

**Comment by NitishKumar06** [comment]
@StackScribe The following links actually point to the same page. Is this the right issue?

**Comment by DavidPHirsch** [comment]
stale
