### ISSUE TITLE
Document how to use trigger load test without using the CD feature

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1157]
I would like to know,  Is it possible to use the trigger load test without using the CD feature?

[Adam Gardner]
Yes, you can pick and choose the parts you use.Your sequence would probably look something like this:

sequence: mysequence
  tasks: 
    - name: load
    - name: evaluation

In that case, your load testing tool would respond to the load.triggered event and after your LT tool signals to Keptn that it is done (via a load.finished event) the quality gate would automatically trigger

This might go into https://keptn.sh/docs/0.13.x/quality_gates/integration/#trigger-a-quality-gate-evaluation-1 -- look around in that section to find the best location.

**Comment by DavidPHirsch** [comment]
outdated
