### ISSUE TITLE
Correct formatting in "Deployment with Helm"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1161]
Fix formatting error in the "Note" for #3 of https://keptn.sh/docs/0.13.x/continuous_delivery/deployment_helm/#user-managed-deployments .

https://keptn.slack.com/archives/CNRCGFU3U/p1648629724553759 

Worth an editorial pass on this section -- I see some syntactic errors in the prose.

**Comment by rghdrizzle** [comment]
hey im new to this community , is anyone working on this issue?

**Comment by DavidPHirsch** [comment]
outdated
