### ISSUE TITLE
Add "Intro to Keptn" to docs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1169]
Use https://dynatrace-my.sharepoint.com/:p:/p/andreas_grabner/EX8xgzdM9ddPlv2NG3kS4IQBP7Qq0LjMDaSxgIySB-eDvA?e=0zcdav for some source then embed a link to Andi's talk.

@StackScribe is working on this

**Comment by DavidPHirsch** [comment]
outdated
