### ISSUE TITLE
Clarify Keptn namespace rules

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1190]
Install docs need good information about Keptn and namespaces.  Someplace, we say that Keptn can share a cluster but must have its own namespace, but I see that the Keptn Full Tour on Prometheus specifies that prometheus-service must be in the same namespace as Keptn, then that monitoring must be in the same namespace as prometheus... 

Need to determine the truth then document it.

**Comment by DavidPHirsch** [comment]
outdated
