### ISSUE TITLE
Clarify order of "Set up Prometheus Monitoring" and "Create first microservice"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1192]
In the Keptn Full Tour on Prometheus, "Create first microservice" is Step 9 but maybe it requires that "Set Up Prometheus Monitoring" (Step 13) be done first so we need to move the Prometheus setup before Step 9.

Alternately, if the best practice is to deploy the apps and get them reporting metrics before setting up prometheus-service, we should briefly outline the approach at the beginning of the process.

Should also compare this material to what is in https://keptn.sh/docs/0.14.x/monitoring/prometheus/install/ -- the two documents are very similar so let's make sure that they match or that they should not match.

See discussion: https://keptn.slack.com/archives/CNRCGFU3U/p1650433242624579

**Comment by DavidPHirsch** [comment]
outdated
