### ISSUE TITLE
Determine installation scenario for FT/Prometheus

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1198]
Section 2 (Bring your own Kubernetes cluster) has a link for tutorials "how to set up your cluster here" that points to Keptn-in-a-box.

Options to solve this:
* Point to "Create or bring a Kubernetes cluster" in the documentation, with remarks about options that are useful for study/demo
* Duplicate the instructions from the docs here (-1)
* Can we use kindkeptn to just give a Docker image that has the k8s cluster plus Keptn installed so the user is quickly able to start the project work?
* Set up katacoda or similar service to provide a pre-installed Keptn environment
* Other?

We should also provide good instructions somewhere about how to incorporate Keptn into an existing Prometheus cluster.  I would favor putting this in documentation (some information is there but it's not ideal) and link to that.

My preference is to somehow provide a working Keptn environment so that the user can quickly begin working with Keptn.  If we want a tutorial about setting up Keptn, it should be separate from this.

**Comment by DavidPHirsch** [comment]
outdated
