### ISSUE TITLE
Remove manual download instructions for Keptn CLI

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1200]
Section 4 includes instructions to manually download the current release of the CLI as well as instructions for installing it with curl and brew.  To simplify the tutorial, we should remove the manual download instructions and point to the documentation for that option.  

Note that this means that the tutorial is problematic for Windows users but, at the end of this section, we say that the rest of the tutorial is really only for Linux/macOS so that seems appropriate.  We should probably put that caveat in Section 1.

**Comment by DavidPHirsch** [comment]
stale
