### ISSUE TITLE
Create "Install Keptn" section

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1201]
Move the installation content that is currently in 0.xx.x/operate into a top-level section and break out individual pages for "Create k8s cluster", "Install Keptn in an existing cluster", "Install CLI and Keptn", etc.  Also include pages about using Helm (which is kind of there but pretty confusing), "Multi-cluster setup", "K8s support & Cluster size", etc

Perhaps include Quick Start as first page in this section?

Top page of each section/subsection should list the steps involved, in order, with links to individual pages as well as relevant general information.  (For example, the section on installing a k8s cluster will briefly discuss the options that are particularly suited for self-study, demos, and development environments; the section on installing Keptn might explain that this can be done manually, using the kindkeptn docker image, or using the helm chart).  The summary lists might include links to pages currently in other sections (e.g. manage/git-upstream, Istio installation in continuous-delivery/expose-services, set up monitoring for Dynatrace/Prometheus) although some effort will be made to consolidate all this information into this section.

Some pages to be included are:
* Install a k8s cluster (list all the options in current docs but include intro that identifies the options that are particularly appropriate for study/demonstration and for development
* Install Keptn in this cluster (including authenticate Keptn CLI and Keptn Bridge)
* Install Keptn in an existing (production) k8s cluster
* Kubernetes support & cluster size
* Configure Helm on Keptn (for exposing the Bridge, customizing ports, etc)
* Troubleshooting

Maybe other topics will be added.

For  detailed explanation of the proposed structure, see https://docs.google.com/document/d/1fQaLxsnIRjHfqzZl-D2vJ8VoeYpaSEdg0CIH9IbmxyU/edit# .

Implementation plan:
* This will be implemented for  the current-plus-2 version of the docs so that it is published for the first time when a new software release is published; this change is too disruptive to be implemented piecemeal is a published doc set.
* We will first create the new section to include the existing material from the installation docs and deleting the old version of those docs.   This first pass will also include a first pass at the section intro information.
* On a subsequent pass, we will incorporate material from other docs (such as tutorials).
* We will then compare these contents with equivalent information included in other docs, especially the tutorials

What Done Looks Like
1. New top-level section entitled "Install Keptn" with comprehensive information for all implementations
2. Duplicate installation material removed from other docs as much as possible

**Comment by DavidPHirsch** [comment]
outdated
