### ISSUE TITLE
Clarify use of Dynatrace dashboard for SLOs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1205]
See discussion in response to questions in https://keptn.slack.com/archives/CNRCGFU3U/p1650549961345889 and existing docs at https://github.com/keptn-contrib/dynatrace-service/blob/master/documentation/slis-via-dashboard.md#slo-tiles /. 

After this is done, https://github.com/keptn/keptn.github.io/issues/1206 should be done as well.

@agardnerIT is a good resource here.

**Comment by agardnerIT** [comment]
1. The full tour on Dynatrace should also include API permissions for `Read SLO`

**Comment by DavidPHirsch** [comment]
outdated
