### ISSUE TITLE
Describe SLI/SLO better in tutorial

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1208]
We need to clarify the relationship of SLIs to SLOs when they create their first SLI in the Full Tour on Prometheus tutorial.  Adding a discussion about what we are doing in this exercise (see https://github.com/keptn/keptn.github.io/issues/1203 ) should help a lot but we might also want to add an explanatory note after they run the project with the SLI but not the SLO defined.

Andreas Grabner provides some useful verbage:

Hi Juergen. Just reading through this and thought to explain a couple of things
1: we differentiate between SLIs (how you query data) and SLOs (what you expect this data to be) - but I think you already figured this out
2: if you do not specify SLOs then it doesnt matter if the SLI doesnt return any value - because - you can define any type of SLIs (indicators) but they are only looked at if you actually use them in the SLO.yaml
Now - what I am not sure of is when your promql returns 0 whether this means 0 (the actual value) or 0 (as in no data). If 0 comes back as a valid number then I think the current implementation of valdating whether 0 < 600 is actually correct. The question really therefore is whether the promql is correctly handling the situation when no data comes back. I am not an expert in Prometheus and I am also not too famliiar with the prometheus-service. Woudl be interesting to check the logs of the prometheus service to see what it says there

**Comment by DavidPHirsch** [comment]
outdated
