### ISSUE TITLE
Fix command to create mykeptn cluster

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1212]
https://keptn.sh/docs/quickstart/#install-keptn has the following command, which does not work, to create mykeptn cluster:
k3d cluster create mykeptn -p "8082:80@loadbalancer" --k3s-server-arg "--kube-proxy-arg=conntrack-max-per-core=0"  --k3s-agent-arg "--kube-proxy-arg=conntrack-max-per-core=0" --agents 1

Christian's video has a different command, which may be the same on shown in https://keptn.sh/docs/0.14.x/operate/install/#create-or-bring-a-kubernetes-cluster . [still getting errors]
k3d cluster create mykeptn -p "8082:80@loadbalancer" --k3s-arg "--no-deploy=traefik@server:*"
Produces following error message:
INFO[0000] portmapping '8082:80' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
ERRO[0000] Failed to get nodes for cluster 'mykeptn': docker failed to get containers with labels 'map[k3d.cluster:mykeptn]': failed to list containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22app%3Dk3d%22%3Atrue%2C%22k3d.cluster%3Dmykeptn%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied 
INFO[0000] Prep: Network                                
ERRO[0000] Failed Cluster Preparation: Failed Network Preparation: failed to create cluster network: failed to check for duplicate docker networks: docker failed to list networks: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks?filters=%7B%22name%22%3A%7B%22%5E%2F%3Fk3d-mykeptn%24%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied 
ERRO[0000] Failed to create cluster >>> Rolling Back    
INFO[0000] Deleting cluster 'mykeptn'                   
ERRO[0000] Failed to get nodes for cluster 'mykeptn': docker failed to get containers with labels 'map[k3d.cluster:mykeptn]': failed to list containers: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22app%3Dk3d%22%3Atrue%2C%22k3d.cluster%3Dmykeptn%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied 
ERRO[0000] failed to get cluster: No nodes found for given cluster 
FATA[0000] Cluster creation FAILED, also FAILED to rollback changes! 

Found the following in the k3d docs:
`k3d cluster create --k3s-arg "--disable=traefik@server:0"

**Comment by DavidPHirsch** [comment]
outdated
