### ISSUE TITLE
How to add tools to Keptn

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1232]
Integrate @Dynatrace-Adam-Gardner 's piece (https://gist.github.com/agardnerIT/9e9f960c13424a8a2e56afa6c803237d) to docs -- summary line: "It's not Keptn versus other tooling but Keptn plus other tools"

This will probably be added to the "Custom integration" section, which may be refactored a bit because of this. 

Meha Bhalodoya is working on this

**Comment by prateek041** [comment]
I would love to work on this issue. Can you tell me a bit more about where in 'docs' in the piece to be added ?

**Comment by DavidPHirsch** [comment]
outdated
