### ISSUE TITLE
Feature of invalidating an evaluation to ignore for further comparison

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#1237]
### Feature documentation
- Since Keptn 0.7.3 it is possible to invalidate an evaluation result. Consequently, it is not considered for comparison. The feature was released with: https://keptn.sh/docs/news/release_announcements/keptn-073/ 

- This is possible via the Bridge. 
  - First, select the evaluation you would like to invalidate from the heatmap.
  - Second, click the **Ignore for comparison** button
![image](https://user-images.githubusercontent.com/729071/169971384-067443e2-e39a-46d3-bc70-7a032391dc8a.png)

- Besides, this is also possible using the API: 
  - Provide the `SH-KEPTN-CONTEXT`, `ID-OF-EVALUATION-TRIGGERED-EVENT`, `PROJECT`, `STAGE`, and `SERVICE` to complete the following JSON payload
  ```
  {  
    "shkeptncontext":"SH-KEPTN-CONTEXT",
    "type":"sh.keptn.event.evaluation.invalidated",
    "triggeredid":"ID-OF-EVALUATION-TRIGGERED-EVENT",
    "source":"manual-invalidation",
    "data":{
      "project":"PROJECT",
      "stage":"STAGE",
      "service":"SERVICE"
    }
  }
  ```
  - Post the following event to the `/event` endpoint using `curl` or the keptn CLI with `keptn send event -f .\event.json`

### Definition of done
- [ ] Documentation is provided to explain how to invalidate an evaluation using Bridge or API (CLI)

**Comment by StackScribe** [comment]
Also info in https://github.com/keptn/keptn/issues/3290 although perhaps of no consequence

**Comment by DavidPHirsch** [comment]
outdated
