### ISSUE TITLE
Create shipyard reference page

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1239]

**Comment by Nawaz027** [comment]
Hey @StackScribe , Can you please elaborate the issue in detail, as I am new to the community it will help me better to understand and take up the issue.
Thanks in advance!

**Comment by StackScribe** [comment]
Hi, @Nawaz027 This has been completed -- my bad for not closing the issue!   You can see what we have at https://keptn.sh/docs/0.16.x/reference/files/shipyard/ .  It definitely needs more work so feel free to submit PRs to improve it.

**Comment by StackScribe** [comment]
https://github.com/keptn/keptn.github.io/pull/1238
