### ISSUE TITLE
Dead Link: SLI Provider creation

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1240]
On this page: https://keptn.sh/docs/0.15.x/quality_gates/sli-provider/

The link to the SLI-provider is dead.

Add custom SLI-Provider
To create and add your custom SLI-provider to Keptn, please follow the instructions [here](https://keptn.sh/docs/integrations/sli_provider).

**Comment by Nawaz027** [comment]
I want to work on this issue. Please assign this to me.
Thanks

**Comment by Nawaz027** [comment]
Hey @StackScribe , I guess the issue has already been resolved. Can you please confirm?

**Comment by agardnerIT** [comment]
Closing as stale
