### ISSUE TITLE
Update the 0.17 upgrade guidelines for refactored helm chart

### ISSUE THREAD

**Issue by mowies** [keptn/keptn.github.io#1267]
In https://github.com/keptn/keptn/pull/7678, the Keptn Helm Chart was refactored heavily. So much so, that we will need specific guidelines on how to upgrade to the next released version of Keptn.

Specifically, the helm values file needs to be adjusted by users and that needs to be documented.

**Comment by StackScribe** [comment]
I am in the process of creating a separate "Installation" section in the docs that has individual pages for the different topics.  Let me get that done and then we'll do this -- and looks at the whole mess, which I expect needs other work for 0.17.x

**Comment by mowies** [comment]
Fixed in https://github.com/keptn/keptn.github.io/pull/1286
