### ISSUE TITLE
Htmltest fails due to release preparations

### ISSUE THREAD

**Issue by aepfli** [keptn/keptn.github.io#1272]
within #1271 the documentation for the next release was prepared and now our testing builds are failing due to missing tags within the keptn project.

```
docs/0.17.x/operate/multi_cluster/index.html
  Non-OK status: 404 --- docs/0.17.x/operate/multi_cluster/index.html --> https://github.com/keptn/keptn/releases/tag/0.17.0
  Non-OK status: 404 --- docs/0.17.x/operate/multi_cluster/index.html --> https://github.com/keptn/keptn/releases/tag/0.17.0
  Non-OK status: 404 --- docs/0.17.x/operate/multi_cluster/index.html --> https://github.com/keptn/keptn/blob/0.17.0/helm-service/chart/README.md#configuration
  Non-OK status: 404 --- docs/0.17.x/operate/multi_cluster/index.html --> https://github.com/keptn/keptn/blob/0.17.0/jmeter-service/chart/README.md#configuration
docs/0.17.x/operate/k8s_support/index.html
  Non-OK status: 404 --- docs/0.17.x/operate/k8s_support/index.html --> https://github.com/keptn/keptn/blob/0.17.0/installer/manifests/keptn/charts/control-plane/templates/core.yaml
docs/0.17.x/operate/install/index.html
  Non-OK status: 404 --- docs/0.17.x/operate/install/index.html --> https://github.com/keptn/keptn/releases/tag/0.17.0
docs/0.17.x/operate/advanced_install_options/index.html
  Non-OK status: 404 --- docs/0.17.x/operate/advanced_install_options/index.html --> https://github.com/keptn/keptn/tree/0.17.0/installer/manifests/keptn
  Non-OK status: 404 --- docs/0.17.x/operate/advanced_install_options/index.html --> https://github.com/keptn/keptn/releases/tag/0.17.0
  Non-OK status: 404 --- docs/0.17.x/operate/advanced_install_options/index.html --> https://github.com/keptn/keptn/releases/download/0.17.0/keptn-0.17.0.tgz
  Non-OK status: 404 --- docs/0.17.x/operate/advanced_install_options/index.html --> https://github.com/keptn/keptn/releases/download/0.17.0/helm-service-0.17.0.tgz
  Non-OK status: 404 --- docs/0.17.x/operate/advanced_install_options/index.html --> https://github.com/keptn/keptn/releases/download/0.17.0/jmeter-service-0.17.0.tgz
docs/0.17.x/continuous_delivery/deployment_helm/index.html
  Non-OK status: 404 --- docs/0.17.x/continuous_delivery/deployment_helm/index.html --> https://github.com/keptn/keptn/tree/0.17.0/helm-service
docs/0.17.x/api/git_provisioning/index.html
  Non-OK status: 404 --- docs/0.17.x/api/git_provisioning/index.html --> https://github.com/keptn/keptn/blob/0.17.0/installer/manifests/keptn/charts/control-plane/values.yaml#L26
========================================================================
```

There are 2 options to circumvent this problem:

1. with less effort but also not checking those urls
2. with efforts for each preparation and release, but checking the urls

## the one with less effort but also less security:

We simply ignore all the urls based on patterns, which contain release tags and number (but this will mean, that we never check them, and that we can introduce errors

## the one with more effort but more secure:

When doing this "prepare" pr, we would need to add the version number to the ignore list for URLs in .htmltest.yml and when releasing we would remove it again. It is not really smooth but could be an option :)

Both ways do work for me, the question is, what does the community want :)

**Comment by aepfli** [comment]
> For this PR, I manually look at the report and verify that the failure was only for expected links that are not yet available. I would suggest following this approach since it is balanced enough between practicality and "security". WDYT @aepfli ? 
by @thisthat in #1271 

I think it will generate more confusion for all the participants, the build will fail for everyone, and the first question will be why? This confusion can be really tricky for contributors. Additionally people might not realize that there is no 14 instead of 13 errors, and the number of errors will grow.

I would suggest to have a way of handling them, either by just adding `- "0.17.0"` to https://github.com/keptn/keptn.github.io/blob/0c4671ea8d276b86ad687634f3c68adcf3db9ddf/.htmltest.yml#L15-L37 

or to ignore the urls with the pattern:
```
- "github.com/keptn/keptn/.*/\\d*\\.\\d*\\.\\d*"
```
which can be seen here: https://github.com/keptn/keptn.github.io/pull/1273

**Comment by mowies** [comment]
As long as the process of adding a new version to the docs is documented somewhere, I would go with the option to manually add the ignored URL to the htmltest config file.
The URL pattern with `github.com/keptn/keptn` will not be enough since none of the cross references will work either since they are not public yet. (I mean the links to `keptn.sh/docs/0.17.x/*`)

**Comment by thisthat** [comment]
Oh sorry, I noticed that I was wrong. I was under the impression that we only check for changed files. 
I agree that a regex should suffice until we have a better website :D

**Comment by aepfli** [comment]
no htmltest can not detect what has changed, as we are checking the "compiled" page, and htmltest does not know what has changed since the "last" compilation as it is hard to get the relation between changed markdown and html in general (for hugo it might work easily)

**Comment by aepfli** [comment]
as 1273 got merged, we can close this issue
