### ISSUE TITLE
Create Concepts article about Job Executor Service

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1277]
May want to put some information into the Concepts/Architecture page as well and add an entry to the Concepts/Glossary page

Source:
* general description: https://github.com/keptn-contrib/job-executor-service/blob/main/docs/INSTALL.md 
* Features: https://github.com/keptn-contrib/job-executor-service/blob/main/docs/FEATURES.md 
* Architecture: https://github.com/keptn-contrib/job-executor-service/blob/main/docs/ARCHITECTURE.md#example-configuration
* Advice from Andi: https://keptn.slack.com/archives/CNRCGFU3U/p1656082499295679 

A stub file that contains links to the content in the software files is included in the PR to create the "Installation" section

**Comment by agardnerIT** [comment]
Is Job Executor Service going to go into the core repo? If so then I agree it lives on official site. Otherwise this doesn't belong on the official site and instead belongs on the JES repo.

**Comment by DavidPHirsch** [comment]
outdated
