### ISSUE TITLE
shipyardController.config.uniformIntegrationTTL option is not doc'ed but is referenced

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1280]
https://keptn.sh/docs/0.16.x/integrations/custom_integration/ references https://keptn.sh/docs/0.16.x/operate/advanced_install_options/ for information about the shipyardController.config.uniformIntegrationTTL option, but that option is not discussed here.

This is related to https://github.com/keptn/keptn.github.io/issues/1112

**Comment by DavidPHirsch** [comment]
stale
