### ISSUE TITLE
Fix broken xrefs in reference/cli source files

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1282]
The restructuring of the Installation docs creates four broken xrefs in the reference/cli docs.  To get https://github.com/keptn/keptn.github.io/pull/1279/ to pass CI, I fixed those in the keptn.github.io repo but those changes will be overwritten the next time the content is overwritten.

These are the files and the correct xref:

* keptn_configure_monitoring, Line 15: See [Monitoring with Dynatrace](../../../../../install/monitoring/dynatrace/install/) for more information.
* keptn_install, Line 14: For more information, please follow the installation guide [Install Keptn](../../../../../install/helm-install) 
* keptn_upgrade, Line 14: For more information, please follow the installation guide [Upgrade Keptn](../../../../../install/upgrade/) 
* keptn_upgrade_project, Line 18: For more information about upgrading projects, go to [Manage Keptn](../../../../../install/upgrade)

**Comment by DavidPHirsch** [comment]
outdated
