### ISSUE TITLE
DIscuss ingress resource in Keptn helm chart

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1283]
(this comment is meant for this whole ingress section in install/access)
We do provide an optional ingress resource directly in the Keptn helm chart.
See: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/values.yaml#L415-L423

Maybe this could be changed in a follow-up task?

_Originally posted by @mowies in https://github.com/keptn/keptn.github.io/pull/1279#discussion_r908110921_

This may be covered in the "Install Keptn using the Helm chart" page (was: https://keptn.sh/docs/0.16.x/operate/advanced_install_options/#install-keptn-with-an-ingress-object ).  The information in these two pages needs to be merged/rationalized for sure!

**Comment by DavidPHirsch** [comment]
outdated
