### ISSUE TITLE
Create reference pages

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1292]
We currently have a Reference section under each project release, which includes:
* Reference pages for all Keptn CLI commands, generated automatically

We also have:
* Reference pages for the Keptn API, although the docs only include instructions for viewing these on ones Keptn installation.  These pages should be viewable from the documentation as well.

We need:
* Reference pages for all Keptn configuration files that users and/or developers access
* Miscellaneous pages for material that doesn't fit elsewhere, such as a page that lists the environment variables that control how the distributor works

The reference section should be pulled out of the release-specific sections since each page will contain a "Differences between versions" section that identifies differences.

See  https://docs.google.com/document/d/1rmSGUFsnYuNc_BGHGmkW-9iB3hrOYbMeA-mJmMOjGRk/edit#heading=h.jwrhldzbo0x6 for the full proposal.

**Comment by DavidPHirsch** [comment]
outdated
