### ISSUE TITLE
Discuss keptn trigger sequence command in guides

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1295]
The `keptn trigger sequence` command is mentioned in https://keptn.sh/docs/quickstart/#outcome and is mentioned in https://keptn.sh/docs/news/release_announcements/keptn-0160/#features and https://keptn.sh/docs/news/release_announcements/keptn-0160/#bug-fixes but is not discussed in the guides.  It should be discussed in https://keptn.sh/docs/0.17.x/manage/triggers/ and perhaps elsewhere.

**Comment by afzal442** [comment]
Hi Meg! Thanks for raising this issue up. 
I think, the link to release you mentioned for `keptn trigger sequence` CLI above is rather [this one](https://keptn.sh/docs/news/release_announcements/keptn-0141/)(v0.14.1).

**Comment by afzal442** [comment]
FYI, I have encountered an another change required in our docs as shown in below is deprecated;
![image](https://user-images.githubusercontent.com/11625672/178156297-77ca5502-c1d3-42cf-9b59-4bb76fad0071.png)
After recent change made to this `keptn trigger sequence`, we need to update the cmd to sth like `keptn trigger hello --project helloworld --service demoservice --stage demo` in the docs as well.
Ref: https://github.com/keptn/keptn/pull/7902

**Comment by afzal442** [comment]
cc @robertjahn

**Comment by DavidPHirsch** [comment]
outdated
