### ISSUE TITLE
Keptn and Other Tools (aka "Keptn vs." page)

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1297]
@mehabhalodiya @StackScribe we drafted such a page. Did anything ever come of including it?

**Comment by mehabhalodiya** [comment]
Yes, I believe we had discussed it earlier and came out with: https://gist.github.com/mehabhalodiya/3a30a4dc5e20a7c1bfd094f0c3d66653

I am not aware if @StackScribe has suggested any changes, or if she wants to add more.
