### ISSUE TITLE
Bridge: Docs for Version Check can not be reached

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn.github.io#1306]
@christian-kreuzberger-dtx commented on [Thu Jul 14 2022](https://github.com/keptn/keptn/issues/8431)

This is with Keptn 0.16, but I guess it also affects 0.15 and 0.14. Keptn 0.13 is the last version that had the URL available.

![image](https://user-images.githubusercontent.com/56065213/178988729-4095a2a4-e050-4113-92eb-de07dfea65b3.png)

The existing URL https://keptn.sh/docs/0.16.x/reference/version_check/ is not reachable and leads to a 404.

**Comment by StackScribe** [comment]
This got missed when we moved the Bridge docs out of the Reference section and to their own section.  The link should be to https://keptn.sh/docs/0.16.x/bridge/version_check/ -- I will fix the docs

**Comment by aepfli** [comment]
I would recommend adding a redirect configuration instead of moving the documentation, as it might change more often with the new doc engine. see https://docs.netlify.com/routing/redirects/ and maybe also adapt it in the `bridge` itself to point to the direct URL.

**Comment by aepfli** [comment]
```
/docs/:version/reference/version_check/ docs/:version/bridge/version_check/
```
within the `_redirects` file should actually do the trick and redirect only, if the file does not exist

**Comment by StackScribe** [comment]
The flaw to solving this problem with a redirect is that the UI is displaying the actual URL for the file and that is still wrong, even if the redirect would take them to the appropriate page.  I think it's better to just fix the URL that is displayed.   Redirects are more appropriate when the link displays the name of the page rather than the URL.

**Comment by aepfli** [comment]
the problem is, that we would need to fix the URL in the old versions too, since it got moved, the links are not up to date, I am not sure how many versions are affected, but the redirect, at least ensures that people will be pointed to the right source anyways.

**Comment by ashutosh887** [comment]
Let me work on this issue @StackScribe 

/assign
