### ISSUE TITLE
Update "CNCF Sandbox Project" references to show the incubating status

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#1328]
There are some references to the CNCF Sandbox in the text and on the images. It would be great to clean them up .

## References

- CNCF Membership SVG: https://github.com/keptn/keptn.github.io/pull/1324
- CNCF Sandbox in contacts: https://github.com/keptn/keptn.github.io/blob/6bb0f329e696c1db96d15ac50d1f639efb8fb610/layouts/partials/contact.html
- Any other references on the materials

**Comment by Omkar0114** [comment]
Hey, @oleg-nenashev @agardnerIT  I would like to work on this one, Can you assign it to me? :)

**Comment by Omkar0114** [comment]
Can anyone assign to me this one?
