### ISSUE TITLE
Clarify what Keptn CLI is and how/where to install it

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1332]
From @agardnerIT :
The keptn CLI != keptn. The CLI is much like kubectl (an interface to the Keptn API).The CLI won’t go on the cluster, it’ll go on the cloud shell machine you use to interact with AKS.

curl -sL https://get.keptn.sh/ | bash

Should install and mv the CLI for you.You might need sudo to move the file but you can run keptn CLI from any directory. Just use ./keptn rather than keptn if you don’t have permission to move the file.Keptn core pods are installed via helm: https://keptn.sh/docs/explore/ (edited)

**Comment by Pratham16112002** [comment]
[Refer this ](https://keptn.sh/docs/0.9.x/operate/install/)
