### ISSUE TITLE
Tidy up footer links

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1344]
The footer links have some duplicated content and the sections are generally outdated as we've added new content

![image](https://user-images.githubusercontent.com/26523841/183271746-c4d57336-d98c-48f1-b2d6-e7db1c2314ff.png)

Remove the duplicates

**Comment by Omkar0114** [comment]
Hey, @agardnerIT I would like to work on this issue!

**Comment by Omkar0114** [comment]
Thanks for assigning me @agardnerIT So what exactly should I do here? Which duplicated terms should I remove? Ones which in the column of `Sitemap` OR `Resources` ?

**Comment by Omkar0114** [comment]
Hey, @agardnerIT I made the changes, can you review it?
