### ISSUE TITLE
"Why Keptn" page should link to "Keptn and others"

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1346]
After reading the "why keptn" page, I'm probably thinking "this sounds like a lot of other tools I know about.

As a new potential Keptn adopter, I might just think "I won't bother because it sounds exactly like tool X".

We should point out to users that Keptn isn't usually a replacement tool but in fact it is designed to work perfectly well with other tools - it complements rather than replaces.

Therefore somewhere on the page (top / bottom?) we should include a sentence / paragraph which explains the above and then links to the [Keptn and other tools](https://keptn.sh/docs/concepts/keptn-tools/) page.

**Comment by StackScribe** [comment]
Totally agree!

**Comment by Omkar0114** [comment]
Hi,  @StackScribe , @agardnerIT 
I would like to work on this issue can you assign it to me ?

**Comment by agardnerIT** [comment]
@Omkar0114 are you still able to work on this?

**Comment by Omkar0114** [comment]
Hi @agardnerIT , 
Yes I'm  working on this. Sorry for not being active as I was busy with college exams. I'll make PR for this 🙂
