### ISSUE TITLE
Retire tutorials.keptn.sh?

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1347]
Should we retire tutorials.keptn.sh, keep it, significantly rework it or something else?

1. The version selector shows me the tutorials are only compatible with 0.11 as the latest version
2. Do we have named maintainers for these tutorials and are they being kept current? Point 1 suggests not
3. The "explore keptn without installation" tutorial is back (AGAIN) and links to the now defunct 4. (issues: https://github.com/keptn/keptn/issues/7280, 

![image](https://user-images.githubusercontent.com/26523841/183272432-052d846f-1ac6-49b3-9ed4-eff2849ba167.png)

**Comment by StackScribe** [comment]
In the 11 August 2022 Community Developer Meeting, we discussed this and agreed that the old tutorials should be retired in favor of the new Killercoda End-to-End tutorial.  @johannes-b is concerned about links that might exist to these tutorials.  The agreement is to remove all content but have the pages say "This content has been deprecated" or whatever then link to the Kilrcoda tutorial
