### ISSUE TITLE
Quickstart helm instructions Chart.yaml missing

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1408]
Following the [Quickstart: Keptn and Prometheus](https://tutorials.keptn.sh/tutorials/keptn-quickstart-011/index.html) tutorial points me to: `https://keptn.sh/docs/quickstart/#install-keptn`

1. Install k3d `4.4.4` with the provided command - ✅ OK
2. `k3d cluster create` command - ✅ OK
3. Download Keptn CLI command - ✅ OK
4. `helm install` keptn core components command - ❌ FAIL

## To Reproduce
Execute the `helm` command given:

```
helm install keptn keptn --repo=https://charts.keptn.sh \
-n keptn --create-namespace \
--set=apiGatewayNginx.type=LoadBalancer \
--set=continuousDelivery.enabled=true \
--wait
```

**Result**
```
user@host:~$ helm install keptn keptn --repo=https://charts.keptn.sh -n keptn --create-namespace --set=apiGatewayNginx.t
ype=LoadBalancer --set=continuousDelivery.enabled=true --wait
Error: INSTALLATION FAILED: Chart.yaml file is missing
```

**Comment by aepfli** [comment]
as we don't have this quickstart anymore, i will close this ticket
