### ISSUE TITLE
keptn upgrade CLI reference not removed from 0.18.x docs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1416]
https://keptn.sh/docs/0.18.x/reference/cli/commands/keptn_upgrade/ is in the documentation although the command has been removed

This is still in the 0.18.x docs.  Let's get it removed for LTS!

**Comment by aakankshabhende** [comment]
@StackScribe Can I work on this issue?

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
