### ISSUE TITLE
No upgrade instructions for 0.17.x to 0.18.x

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1417]
https://keptn.sh/docs/install/upgrade/ contains instructions for upgrading from 0.16.x to 0.17.x but no instructions to upgrade from 0.17.x to 0.18.x.

We actually don't have any "basic" upgrade instructions.  We used to have the keptn upgrade reference page (actually, we still do -- separate problem!) and we have instructions for upgrading the helm chart in an air-gapped environment (https://keptn.sh/docs/install/helm-install/#execute-helm-upgrade-without-internet-connectivity) but buried at the bottom of the helm installation page.

Here is my proposal for modifying the https://keptn.sh/docs/install/helm-install/#execute-helm-upgrade-without-internet-connectivity page:
* Begin with caveat that you need to upgrade one release at a time -- not try to skip from 0.11.x to 0.18.2 in one fell swoop
* Recommend reading Release Notes before upgrading
* Show basic helm upgrade command -- it should be similar to the command shown for the 0.16.x to 0.17.x but I don't know if one always needs to specify the helm chart or only if one has modified it.  What if I customized the helm chart for the old release -- perhaps a bigger size or something.  I probably need to apply those changes to the new helm chart, right?  And use any --set options I specified for old release.
* Should I mention that they may need to upgrade integrations they are using, or docker images used, etc?  I don't want to go into details but it would be nice to be comprehensive about what may be required.
* Move info about upgrading in air-gapped/offline environment here -- or should we make this a separate page that is right after this one since it is somewhat big and not relevant to most users?
* Then have subsections with details about specific upgrades -- we have excellent material for 0.16.x to 0.17.x
* Are there any specific issues that should be documented for 0.17.x t 0.18.0/0.18.2?

**Comment by oleg-nenashev** [comment]
I believe it was fixed: https://keptn.sh/docs/install/upgrade/#upgrade-from-keptn-0-17-x-to-keptn-0-18-x

**Comment by StackScribe** [comment]
@thisthat Confirmed that we do not have manual upgrade steps required from 0.17.x -> 0.18.x, nor for 0.18.x -> 0.17.x.  The "Upgrade" section has been restructured to have general upgrade information with subsections for each recent release and a table that links to upgrade instructions and release notes for older releases.
