### ISSUE TITLE
Bring Integrations Page into Compliance with Allowed Values

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1419]
The [Keptn spec on artifacthub](https://github.com/artifacthub/hub/blob/master/docs/keptn_annotations.md) shows the following values are possible:

- `webhook`
- `testing`
- `deployment`
- `notification`
- `observability`
- `remediation`
- `sli-provider`

The Keptn website only shows selectors for:
- `testing`
- `deployment`
- `observability`
- `webhook`

This issue is to track the addition of:

- `notification`
- `remediation`
- `sli-provider`

This can be done by adding new values similar [to this older PR](https://github.com/keptn/keptn.github.io/pull/1075/files).

**Comment by Omkar0114** [comment]
Hey, @agardnerIT are you working on this issue?
