### ISSUE TITLE
Add FinOps and Security Integration Categories

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1420]
This issue suggests and tracks work to add two new categories on the Keptn Docs site:

- FinOps (financial operations: tooling and integrations related to cost or financial cloud management)
- Security (tooling and integrations related to security)

# How?

Make changes similar to the ones on this PR: https://github.com/keptn/keptn.github.io/pull/1075

# Other Info

Merging this issue ideally should co-ordinated with a merge of this: https://github.com/keptn-contrib/artifacthub/issues/169

**Comment by Omkar0114** [comment]
Hi, @agardnerIT I would like to work on this one!

**Comment by agardnerIT** [comment]
@TannerGilbert can you confirm that the filtering works on the `keywords` block of the `artifacthub-pkg.yaml` and not (as I originally expected) the `annotations.keptn/kind` property?

@StackScribe some info for the [CONTRIBUTING](https://github.com/keptn-contrib/artifacthub/blob/main/CONTRIBUTING.md) page when @TannerGilbert confirms.

**Comment by agardnerIT** [comment]
A secondary piece of work to come off the back of this will be to ensure every integration has correct `keywords` set. For example, `dynatrace-service` isn't tagged with `sli-provider` yet so that filter would come up empty.

**Comment by TannerGilbert** [comment]
Hey, @agardnerIT, as mentioned in #1075, the filtering currently uses `ts_query_web`, which filters using a full-text search as to my knowledge, there currently isn't a way to filter by an annotation like `keptn/kind`. 

More information about the search:
![ah_search](https://user-images.githubusercontent.com/36239763/188373012-2eda8669-ca77-42a7-9b08-9903485f8dee.png)

Available search filters:
`https://artifacthub.io/packages/search?kind=10&org=keptn&repo=keptn-integrations&license=Apache-2.0&ts_query_web=keptn&ts_query=monitoring&deprecated=true&verified_publisher=true&sort=relevance&page=1`
![Screenshot from 2022-09-05 08-19-02](https://user-images.githubusercontent.com/36239763/188373196-6f39b1e3-6e57-47e1-bbc9-fe4ff8441d21.png)

@Omkar0114, to add the two new categories as suggested in this issue, please add two buttons like in #1075.

**Comment by agardnerIT** [comment]
@Omkar0114 are you still able to work on this or should I complete it?

**Comment by Omkar0114** [comment]
Sorry for the inconvenience adam. I am facing some pushing issues with my local machine so you can go ahead with this! @agardnerIT
