### ISSUE TITLE
Update text on "Integrations" landing page

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1438]
The text under the cards on the "Integrations" page should be updated:
* Keptn is tool-agnostic and can work with almost any tool -- link to "Keptn and other tools" (https://keptn.sh/docs/concepts/keptn-tools/)
* Many tools can be integrated with JES or Webhooks (give doc links)
* Then use the existing information about requesting an integration or creating an integration.

**Comment by DavidPHirsch** [comment]
stale
