### ISSUE TITLE
Setup Dynatrace bug (restarting pods breaks Jenkins)

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn.github.io#144]
https://github.com/keptn/keptn.github.io/blob/1606983e082cac731de23e33fd1ab9fff02a3943/content/docs/0.2.1/monitoring/dynatrace/index.md#L54

Suggests that we restart (delete) all pods but that breaks Jenkins:

1. If Jenkins becomes available again, it  takes Jenkins a **long** time to become available again.
    a) First attempt, Jenkins restarted after 20 mins with a blank new job page.
    b) Second attemp, Jenkins still hasn't started after 50 mins.

```
adam@bastion:~/keptn/install/scripts$ ./deployDynatrace.sh
# This completes successfully.

adam@bastion:~/keptn/install/scripts$   kubectl delete pods --all -n keptn
pod "authenticator-jfw9p-deployment-c77c8bb68-twfnh" deleted
pod "control-zswg5-deployment-7f77ccd6b6-hkxx6" deleted
pod "docker-registry-66bb5d6d98-jgxt4" deleted
pod "event-broker-86msz-deployment-644d9b866f-44xzs" deleted
pod "event-broker-ext-zmkws-deployment-5b46bf9645-b2jpj" deleted
pod "github-service-dmr4z-deployment-5b6c5d86b6-s9nx9" deleted
pod "jenkins-deployment-d9d5d95d9-n6qhl" deleted
pod "jenkins-service-7xqqz-deployment-7447bc767d-qss7w" deleted

adam@instance-1:~/keptn/install/scripts$ kubectl get pods -n keptn
NAME                                                 READY   STATUS    RESTARTS   AGE
authenticator-jfw9p-deployment-c77c8bb68-mkt9x       2/3     Running   0          50m
control-zswg5-deployment-7f77ccd6b6-74ksw            2/3     Running   0          50m
docker-registry-66bb5d6d98-288j7                     2/2     Running   0          50m
event-broker-86msz-deployment-644d9b866f-t69gf       2/3     Running   0          50m
event-broker-ext-zmkws-deployment-5b46bf9645-7k2nl   2/3     Running   0          50m
github-service-dmr4z-deployment-5b6c5d86b6-qj5t7     2/3     Running   0          50m
jenkins-deployment-d9d5d95d9-v254d                   2/2     Running   0          50m
jenkins-service-7xqqz-deployment-7447bc767d-njkmk    2/3     Running   0          50
```
![image](https://user-images.githubusercontent.com/13639658/58156334-34e92780-7cb9-11e9-8ed8-d832a2b2d73e.png)

**Comment by jetzlstorfer** [comment]
Hi Adam, thanks for opening an issue. 
I will update the docs as follows: deleting all pods in the keptn namespace is not needed, since our main goal is not monitornig keptn itself, but in fact monitoring all services that are onboarded to keptn. In our use case this means all pods in the dev, staging, and production namespace (if you follow our onboarding the carts service use case).

**Comment by jetzlstorfer** [comment]
Fix in the PR153, closing issue.
