### ISSUE TITLE
Discuss structure of landing page for LTS docs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1447]
The Keptn-LTS documentation will initially be built using Hugo although we may move it to Docusaurus later.  I would still like to rearrange the docs so that the sections under the 0.19.x, 0.18.x, etc are on the same level as "Concepts" and other docs.
* This establishes the structure we will use under Docusaurus and will simplify the migration to Docusaurus
* We will no longer need to maintain the xrefs that have the specific version in their path (like from Concepts to other sections
* The big job of fixing the xrefs after restructuring the files will be done now and should speed the migration to Docusaurus when the tools are ready

We have a choice here:

* Create a 1.0.x section at the same level as 0.19.x and move Concepts, Installation,  etc into that section
* Move the subsections to 0.19.x out so they are on the same level as Concepts, Installation, etc

Please record your opinions as comments to this issue before the Community Meeting on Wednesday, 12 October or come to the meeting to discuss so I can begin the work

**Comment by oleg-nenashev** [comment]
Why do we need to long feedback cycle? I would suggest making a decision at tomorrow's community meeting

**Comment by oleg-nenashev** [comment]
> Create a 1.0.x section at the same level as 0.19.x and move Concepts, Installation, etc into that section

I vote for that. It is important to have an opportunity to add more documentation entries on the top level. We have sub-rpoejcts like Keptn Lifecycle Controller and maybe Lighthouse, and IMO it is important to be able to have documentation roots for them.

Also, a correct version could be `lts-1.0.x` or so
