### ISSUE TITLE
Discuss using Kilrcode exercise as "Quickstart"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1448]
We have retained the "Quickstart" title in the docs for the old exercise which I don't think works.  For the Keptn-LTS docs, I'd like to remove that and rename the "Explore Keptn" exercise (https://keptn.sh/docs/explore/) to be QuickStart.

Does anyone object?  Please post opinions to this issue before the Community Meeting on Wednesday, 12 October or come to the meeting to discuss.  I hope we'll have a consensus by then so I can implement the change.

**Comment by agardnerIT** [comment]
No objections from me

**Comment by oleg-nenashev** [comment]
+1 from me. Maybe makes sense to archive it to a separate page or to add the disclaimer, but the Quickstart should only have the operational content

**Comment by StackScribe** [comment]
In the 12 October 2022 Community meeting, we discussed this and agreed to rename the kilrcoda exercise to be Quickstart.  See https://github.com/keptn/keptn.github.io/issues/1464
