### ISSUE TITLE
Evaluate "Full Tour on Prometheus" tutorial

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1453]
The Kilrcoda End-to-End exercise covers everything in this tutorial and more and I see that this one is not up-to-date.  I was thinking that someone had recently updated this tutorial but not sure -- it looks like this one is using 0.11.x and sockshop and I saw a note that the upstream git repo is optional, albeit recommended.

https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus-011/index.html?index=..%2F..index#0

**Comment by agardnerIT** [comment]
This is no longer maintained in favour of the Keptn Lifecycle Toolkit (if you are k8s-native and looking for a GitOps-based approach) or the [Keptn v1 Killercoda demo](https://bit.ly/keptnv1demo).

Closing.
