### ISSUE TITLE
Evaluate "Keptn Full Tour on Dynatrace"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1456]
https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-011/index.html?index=..%2F..index#0

I am pretty sure that this tutorial is totally broken for current releases.  I also question whether we really need a high-level intro to Keptn for each observability platform -- it seems to me that the End-to-End tutorial is good for showing how Keptn works for any data source.

However, if someone really wants a separate exercise for Dynatrace, the End-to-End tutorial is structured so that everything that is observability-platform-specific is in one unit so we could use that tutorial but fork the exercise to cover different observability platforms.  If you want to do this, work with @afzal442 to work out the implementation details.

**Comment by agardnerIT** [comment]
This is no longer maintained in favour of the [Killercoda demo](https://bit.ly/keptnv1demo) or the [Keptn Lifecycle Toolkit](https://lifecycle.keptn.sh) if you are looking for a GitOps / k8s-native approach.

Closing.
