### ISSUE TITLE
Evaluate "Multi-stage w/Argo Rollouts, Dynatrace, k3s"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1457]
https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-11-on-k3s/index.html?index=..%2F..index#2

**Comment by johannes-b** [comment]
I reached out to @grabnerandi who is the author of the tutorial.

**Comment by agardnerIT** [comment]
Anyone arriving here from Google - the [Keptn Lifecycle Toolkit](https://lifecycle.keptn.sh) is your go-to for GitOps based work with Keptn.
