### ISSUE TITLE
Create excellent installation instructions

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1463]
The old Keptn tutorials were often used as guides to installing Keptn, either for study/demonstration purposes or for a production Keptn instance.  This was never a good use of the tutorials for the following reasons:

* Tutorials are extremely expensive to create and maintain and should only be used for topics that warrant them
* Installation instructions in the tutorials often took shortcuts to simplify the installation process for the demo, but this could lead to installations that had security vulnerabilities or other characteristics that made them less robust than they should be for production sites.

The solution is to provide excellent installation instructions in the documentation, perhaps incorporating videos and, if truly warranted, a tutorial.

We have already begun this process by creating a separate "Installation" section with a number of sub-pages in the documentation and moving all installation instructions for all possible elements into this section.  A few bits of installation instructions are still scattered around the other docs and these need to be incorporated here.  Other doc pages should link to the materials in the main Installation section so we do not have duplication and conflicting information.  In some cases, an installation task can be accomplished in different ways and that should be reflected in the Installation docs, possibly with notes about when one approach might be better than the others.

The landing page of the "Installation" section has a list of required and optional installation tasks, in the order they should be done, with links to the pages that have more details.  This list and the pages in this section need the following improvements:

* Be sure that the list is in the right order and includes all possible topics
* Include information about installation for demos/study and production instances and clearly identify practices that may be acceptable for a demo/study environment but are discouraged for a production environment.
* Expand information about verifying the success of the installation at various stages
* Expand troubleshooting information about the installation and installation sub-topics.

I have assigned this task to myself for oversight but we will need contributions from many people as we go forward.  Please comment if you are interested.

**Comment by DavidPHirsch** [comment]
close as not planned
