### ISSUE TITLE
Restructure "core" documentation under LTS-ish header

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1465]
https://github.com/keptn/keptn.github.io/issues/1447 

Keptn LTS documentation sections will all be located under an LTS-ish header (specific title TBD), with all major sections at the same level.  This means that Quickstart, Concepts, Installation, etc will be on the same level as "Operate", "Manage", et cetera.

**Comment by oleg-nenashev** [comment]
Notes:

- The current documentation under the root will remain the same => no links will be broken, no redirects needed
- @StackScribe will copy the documentation into the LTS branch

![image](https://user-images.githubusercontent.com/3000480/198229771-79a7ccfa-520d-479a-aefa-7f652042aea7.png)

**Comment by agardnerIT** [comment]
Closing as this was moved to done
