### ISSUE TITLE
Add "Create project with API" to docs

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1467]
https://keptn.slack.com/archives/CNRCGFU3U/p1665564823013049 has some information from a user who is having trouble creating a project from the API.

"Start a Project" (https://keptn.sh/docs/0.19.x/manage/project/) has "Create a project from the Keptn Bridge" and "Create a project from the CLI command line" .  Need to add "Create a project from the API" here.

**Comment by DavidPHirsch** [comment]
close as not planned
