### ISSUE TITLE
Update shipyard reference page with version information

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1468]
Add a table that maps shipyard versions to Keptn releases in the `apiVersion` description on the shipyard reference page (https://keptn.sh/docs/0.19.x/reference/files/shipyard/)

While in the file, fix the formatting for the "Metadata" chunk -- probably missing a blank line before the bullet list starts.

**Comment by DavidPHirsch** [comment]
close as not planned
