### ISSUE TITLE
Show that Keptn supports k8s v1.24 

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1469]
https://keptn.sh/docs/install/k8s-support/ does not reflect Keptn releases > 0.17.x and does not show support for k8s v1.24 although it is implemented.

This doc probably deserves a serious critique before Keptn LTS.  It might be nice to retain information about k8s support for the last couple releases, though.
* Explanation of releases should talk about LTS
* Does anyone care about how many resources are required to run sockshop?
* Does the execution plane run on all k8s versions
* What about performance ramifications of running, say, three services on a single execution plane cluster versus setting up a multi-cluster configuration so each service has its own cluster. Traditionally, performance was enhanced by not having multiple services share and compete for resources but that may not be true here.
* Can we also include some guidance here about adequate resources for PVCs?  We are getting a lot of postings in the #help channel that are caused by inadequate resources for the PVCs.  I have added info about this to install/troubleshooting but it might be nice to include something in this page as well.  I used Andi's recommendation of allowing at least 20GB storage for the PVC.  Perhaps we could expand that recommendation -- something like "plus an additional 20GB for each service that creates a mongodb...".  I know that we can't do very specific numbers but it seems we could provide more "soft guidance" than we do..

@thisthat If you want to just provide the information here then reassign the issue to me for scribal services, that is fine.

**Comment by DavidPHirsch** [comment]
stale
