### ISSUE TITLE
Update architecture jpg

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn.github.io#148]
Channels in architecture.jpg needs to be updated to reflect current channel list:

https://github.com/keptn/keptn.github.io/blob/master/content/docs/0.2.1/concepts/architecture/assets/architecture.jpg

https://github.com/keptn/keptn/blob/edbae83257a2f6c78dba7da1adf4ffa8135e5b04/core/eventbroker-ext/src/lib/types/KeptnRequestModel.ts#L5

Remove the _next_ channel and add _new artifact_.

**Comment by johannes-b** [comment]
Hello Adam, 
thanks for your hint to update the architectural diagram in the Keptn documentation. 

We have now updated this section (please see: https://keptn.sh/docs/0.5.0.beta/concepts/architecture/) to reflect the current status of the Keptn internals.

Consequently, I will close this issue.
