### ISSUE TITLE
Add support for the sub-projects on the website layout

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#1485]
It would be nice to list our key sub-projects and working groups in the project, maybe similar to Jenkins' Community and Sub-project tabs... but better in a single meny entry. 

## Acceptance criteria

- [ ] A menu entry is added for the Projects
- [ ] A footer entry is added too
- [ ] Nice2have: Additional page with a listing of the community structure

## Examples

![image](https://user-images.githubusercontent.com/3000480/198233324-f7e8f242-fae8-4bbb-9c36-27cd6c26020d.png)

![image](https://user-images.githubusercontent.com/3000480/198233372-76e5d423-b859-4727-a9da-3eb9eddf6c3e.png)

**Comment by rakshitgondwal** [comment]
Hey! @oleg-nenashev. I would like to work on this. Please assign this to me.

**Comment by ashutosh887** [comment]
Let me work on this issue @oleg-nenashev

/assign

**Comment by DavidPHirsch** [comment]
close as not planned
