### ISSUE TITLE
Improve/update Webhooks documentation

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1487]
Need to review and revise the Webhook documentation (https://keptn.sh/docs/0.19.x/integrations/webhooks/ and https://keptn.sh/docs/0.19.x/integrations/webhooks/jenkins/) to ensure that it accurate and complete for LTS:

* Be sure that everything says makes sense for Webhooks as a "core service"
* For the Jenkins section, clarify that this is about how to set up Webhooks for any CI-CD product and we are just using Jenkins as an example
* Include a note in the Jenkins piece about whether Jenkins calls Keptn or Keptn calls Jenkins.  The existing text just says that Keptn should call Jenkins but does not say that it could be the other way around and why we recommend that Keptn calls Jenkins
* Include information about verifying the Webhook and provide any troubleshooting hints we have
* Tighten up a bit of the prose

**Comment by DavidPHirsch** [comment]
close as not planned
