### ISSUE TITLE
Write intro to "Integrating Tools"

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1492]
The "Integrating Tools" section needs an intro that discusses creating an integration versus JES versus webhooks, and then there are SLI providers and Action providers,  This needs an intro that talks about when to use which facility, etc.  And maybe pull in the api extensions page as well.

**Comment by meenaljain0303** [comment]
I would like to do it, please assign it to me.

**Comment by DavidPHirsch** [comment]
close as not planned
