### ISSUE TITLE
docs/concepts/quality_gates links to 0.18.x

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1496]
`https://keptn.sh/docs/concepts/quality_gates/` still links to `0.18.x` not `0.19.x`

**Comment by aepfli** [comment]
https://github.com/keptn/keptn.github.io/pull/1560 should prevent this forever

**Comment by rakshitgondwal** [comment]
Is this issue still open for grabs?

**Comment by rakshitgondwal** [comment]
Thank you for assigning me this @agardnerIT!
I just need to make the links point to `1.*` in `docs/concepts/quality_gates` right?
