### ISSUE TITLE
https://keptn.sh/docs/0.19.x/reference/files/sli/ should link to spec

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1497]
https://keptn.sh/docs/0.19.x/reference/files/sli/ should link to the SLI spec: https://github.com/keptn/spec/blob/master/service_level_indicator.md

**Comment by bhavyastar** [comment]
Hey @agardnerIT I want like to work on this issue! Would you please assign me?

**Comment by aepfli** [comment]
Hey @bhavyastar, I assigned you. If you do need help, etc., please let us know.

**Comment by aepfli** [comment]
It seems like this is also somewhat related/similar to https://github.com/keptn/keptn.github.io/issues/1528 and might be also worth taking a look - what do you think @StackScribe, those look really similar, and might be fixed as one :)
