### ISSUE TITLE
Announcements hyperlinks seem flaky / unclickable

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1506]
Notice the lack of hand mouse point even of hovering a link.

The top two links sometimes work but the 0.19.x link will not work for me no matter what I do.

chrome 107

![image](https://user-images.githubusercontent.com/26523841/200082096-209b719c-35d3-4fef-a98b-1da77a4b0237.png)

**Comment by agardnerIT** [comment]
This seems to be resolved with #1505 - presumably due to adding the (currently missing) ending `</li>` tags.

**Comment by meenaljain0303** [comment]
if the issue is still opne, kindly assign it to me.
