### ISSUE TITLE
Update supported version info for Integrations

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1537]
The documentation page for each Integration listed at https://keptn.sh/docs/integrations/ identifies the Keptn releases for which the Integration is supported.  When appropriate, they should include a table that shows which versions of the Integration software works with which Keptn version.  This information has not been maintained but needs to be sanitized for LTS.  I expect that an Enterprise user would not install an Integration on their Keptn cluster that is not identified as supported for LTS 1.0.

**Comment by StackScribe** [comment]
This is a quick inventory of the Integrations that are listed with the version information provided for each and a couple other comments. 

Github Actions Webhook Integration (https://artifacthub.io/packages/keptn/keptn-integrations/githubaction) -- No versioning info at all

Akamas webhook integration (https://artifacthub.io/packages/keptn/keptn-integrations/akamas) -- No versioning info at all

Argo Service (https://artifacthub.io/packages/keptn/keptn-integrations/argo-service) -- Stops at Keptn 0.17.x

Argo Service JES (https://artifacthub.io/packages/keptn/keptn-integrations/argo-service-jes) -- Says it is for Keptn 0.18.x only

Artillary Service (https://artifacthub.io/packages/keptn/keptn-integrations/artillery-service) -- Good through Keptn 0.8.5

Asana (https://artifacthub.io/packages/keptn/keptn-integrations/asana) -- Vague versioning info -- Keptn 0.10.0-0.17.0

AWS App Runner (https://artifacthub.io/packages/keptn/keptn-integrations/aws-app-runner) -- Keptn 0.15.0

AWS Lambda (https://artifacthub.io/packages/keptn/keptn-integrations/aws-lambda) -- Keptn 0.10.0-0.15.0

Cloud Custodian (xhttps://artifacthub.io/packages/keptn/keptn-integrations/cloud-custodian-integration) -- Keptn 0.10.0-0.13.4

datadog-service (https://artifacthub.io/packages/keptn/keptn-integrations/datadog-service) -- Keptn 0.19.x

Dynatrace (https://artifacthub.io/packages/keptn/keptn-integrations/dynatrace-service) -- Keptn 0.16.x

Helm Job-Executor Integration (https://artifacthub.io/packages/keptn/keptn-integrations/helm) -- Keptn 0.17.x (This page should explain the history of Helm in Keptn -- baked into 0.18.x and earlier, separate for 0.19.x and later, and that if you upgrade from 0.18.x to 0.19.x and beyond, you keep the old version of Helm but probably should install and implement the current version)

IFTTT (https://artifacthub.io/packages/keptn/keptn-integrations/ifttt) -- Keptn 0.10.0-0.12.0

Infracost (https://artifacthub.io/packages/keptn/keptn-integrations/infracost) -- Keptn 0.10.x-0.19.x

Jenkins Shared Library (https://artifacthub.io/packages/keptn/keptn-integrations/jenkins-library) -- Keptn 0.10.0-0.12.0 and this is right -- text explains that this is not for more current Keptn releases and points to an alternative for later versions

Jenkins Webhook (https://artifacthub.io/packages/keptn/keptn-integrations/jenkins-webhook) -- Keptn 0.12.x-0.19.x

Jira (https://artifacthub.io/packages/keptn/keptn-integrations/jira-service) -- Keptn 0.8.0-0.8.5

JMeter Job-Executor Integration (https://artifacthub.io/packages/keptn/keptn-integrations/jmeter) -- Keptn 0.17.x (This page should explain the history of JMeter in Keptn -- baked into 0.18.x and earlier, separate for 0.19.x and later, and that if you upgrade from 0.18.x to 0.19.x and beyond, you keep the old version of JMeter but probably should install and implement the current version)

Job Executor Service (https://artifacthub.io/packages/keptn/keptn-integrations/job-executor-service) -- Keptn 0.18.x

k6 Load Testing Integration (https://artifacthub.io/packages/keptn/keptn-integrations/k6-keptn-integration) -- Keptn 0.10.0-0.15.0

Litmus (Chaos) Service (https://artifacthub.io/packages/keptn/keptn-integrations/litmus-service) -- Keptn 0.8.4-0.8.7

Locust Service (https://artifacthub.io/packages/keptn/keptn-integrations/locust-service) -- Keptn 0.12.x-0.14.x

Metric Exporter (https://artifacthub.io/packages/keptn/keptn-integrations/metric-exporter) -- Keptn 0.10.0-0.18.x

Microsoft Teams Integration (https://artifacthub.io/packages/keptn/keptn-integrations/microsoft-teams-integration) -- Keptn 0.8.0-0.14.1

Monaco (https://artifacthub.io/packages/keptn/keptn-integrations/monaco-service) -- Keptn 0.9.1

Monday.com (https://artifacthub.io/packages/keptn/keptn-integrations/monday.com-integration) -- Keptn 0.10.0-0.13.4

NeoLoad Webhook Integration (https://artifacthub.io/packages/keptn/keptn-integrations/neoload) -- Keptn 0.10.0-0.13.0 (Is this like Jenkins, that we have an integration for older releases and one for newer releases that support Webhooks?)

NeoLoad (https://artifacthub.io/packages/keptn/keptn-integrations/neoload-service) -- Keptn 0.8.0 (see comment above)

osTicket (https://artifacthub.io/packages/keptn/keptn-integrations/osticket-integration) -- Keptn 0.10.0-0.13.4

PowerShell (https://artifacthub.io/packages/keptn/keptn-integrations/powershell) -- Keptn 0.10.0-0.18.1

Prometheus (https://artifacthub.io/packages/keptn/keptn-integrations/prometheus-service) -- Keptn 0.18.0 (Only???)

ServiceNow (https://artifacthub.io/packages/keptn/keptn-integrations/servicenow-service) -- Keptn 0.8.0-0.8.3

Shell Script (https://artifacthub.io/packages/keptn/keptn-integrations/shell) -- Keptn 0.10.0-0.13.1 (Huh?  This uses JES)

Slack Webhook Integration (https://artifacthub.io/packages/keptn/keptn-integrations/slack) -- Keptn 0.10.x (Yup, that's what it says -- no other Keptn releases, and who knew that Webhooks were available in 0.10.0?

sumologic-service (https://artifacthub.io/packages/keptn/keptn-integrations/sumologic-service) -- Keptn 0.15.x)

Trello (https://artifacthub.io/packages/keptn/keptn-integrations/trello-integration) -- Keptn 0.10.0-0.13.4

Unleash (https://artifacthub.io/packages/keptn/keptn-integrations/unleash-service) -- Keptn 0.14.2-0.16.0

Wrike.com (https://artifacthub.io/packages/keptn/keptn-integrations/wrike-integration) -- Keptn 0.10.0-0.15.0

Zapier (https://artifacthub.io/packages/keptn/keptn-integrations/zapier-integration) -- Keptn 0.8.0-0.12.0

Zendesk (https://artifacthub.io/packages/keptn/keptn-integrations/zendesk-integration) -- Keptn 0.10.0-0.13.4

**Comment by StackScribe** [comment]
The source code has been updated but the doc "Integrations" page has not been updated.

**Comment by DavidPHirsch** [comment]
close as not planned
