### ISSUE TITLE
Make Keptn Governance Committee available on the site

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1544]
Keptn now has a governance committee. Currently it is only shown on [this comment on GitHub](https://github.com/keptn/community/issues/185#issuecomment-1328676857).

I understand there will be tasks to document this more fully, but most likely those documents will remain on GitHub.

I feel that it is important to be upfront and transparent about the governance committee members and the timings of terms - so this issue proposes that this information is directly accessible via the main Keptn website (and any sub-websites that appears forthwith).

I feel that this transparency is important for v1.0.0

**Comment by agardnerIT** [comment]
@aepfli @DavidPHirsch before I start on this, I see https://github.com/keptn/community/pull/247 and then it is reverted https://github.com/keptn/community/pull/251. How should we proceed with this?

**Comment by aepfli** [comment]
i am actively workin on a different approach for KLT - https://github.com/keptn/lifecycle-toolkit/pull/1077 - which we should also apply to the main site afterwards. this way, we can have it on one page. also see - https://github.com/keptn/community/pull/258 where i try to get the community repo into a renderable shape :)

**Comment by DavidPHirsch** [comment]
close as not planned
