### ISSUE TITLE
Evaluate/update helm-service references

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1546]
helm-service is embedded in Keptn in older releases but, in 0.19.x and later, it is a free-standing service.  Need to look for the helm-service string and be sure that the information is clear and up-to-date.  To whit:
* The Integrations page does not list helm-service, only instructions for how to run Helm using JES
* The install doc makes no reference to using something other than helm.  Maybe we don't have a viable alternative at this point and using an alternative is just a hypothetical?
* The "Install with Helm" page in the docs shows how to install helm-service on the Execution plane using the helm command to pull the service from github.  It does not mention the possibility of running helm with JES nor give instructions
* Lots of descriptive bits that talk about what helm-service does should perhaps use a different term (Helm service?) that can apply to both helm-service and Helm run under JES.

**Comment by DavidPHirsch** [comment]
close as not planned
