### ISSUE TITLE
Provide a better way to guide visitors of the keptn website to choose between Keptn and Lifecycle Toolkit

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn.github.io#1552]
As Keptn 1.0 LTS is released and as we also have Keptn Lifecycle Toolkit for more GitOps and Cloud Native Teams I would like to propose a new landing page on keptn.sh go guide visitors towards the right starting point.

Here is a proposal that explains
a) what keptn does
b) who should start with Keptn Lifecycle Toolkit
c) who should start with Keptn V1

![image](https://user-images.githubusercontent.com/675886/208485052-695a62c2-4581-4d4a-9bee-1ec5d7dba4d7.png)

**Comment by agardnerIT** [comment]
See also #1590
