### ISSUE TITLE
"Tutorials" page has self-referential links

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1564]
The "Tutorials" page (https://tutorials.keptn.sh/ ) linked from the tab on top of the Keptn V1 docs has a "Learning path" section that has links that actually just return one to the "Tutorials" page.  These should be fixed or we should just delete the "Learning path" section -- we do not have enough content to warrant this and do not plan to invest more to improve this page.

**Comment by aepfli** [comment]
https://github.com/keptn/tutorials/blob/3fd0f1a35f5934eb567a8352d562f2e6d8d59b8b/site/app/views/default/index.html#L129-L139 

it is pure html

**Comment by Amishakumari544** [comment]
Hi working on this issue @StackScribe

**Comment by Amishakumari544** [comment]
Hi @StackScribe can you please tell me the location where its need to remove?
