### ISSUE TITLE
Promote @aepfli as maintainer of the repository

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn.github.io#1565]
@aepfli showed great involvement and technical leadership for this project. Hence, I suggest to promote him as maintainer of this repository.

**Comment by StackScribe** [comment]
I concur totally!  @aepfli has contributed some very useful features and shows good knowledge and judgement and should be promoted to maintainer of this repository.

**Comment by thisthat** [comment]
Promotion done! Thanks @aepfli for your contribution 🙌
