### ISSUE TITLE
Update Bridge/OAUTH docs to reflect login port enhancement

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1569]
https://github.com/keptn/keptn/pull/9393/ expands how port assignment is handled when implementing OAUTH for the Keptn Bridge.  The https://keptn.sh/docs/1.0.x/bridge/oauth/ page needs to be updated as well; it includes a reference to port 3000, probably needs a bit more discussion about ports.

**Comment by ashutosh887** [comment]
Please let me work on this Issue @StackScribe 

/assign

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
