### ISSUE TITLE
killercoda problems

### ISSUE THREAD

**Issue by jwenz723** [keptn/keptn.github.io#1579]
I recently went through the killercoda [Keptn End-to-End Delivery](https://killercoda.com/keptn/scenario/keptn-end-to-end-delivery) tutorial. Great job creating this tutorial!

Here are a few problems I experienced during the tutorial:

1. The `~/setup_keptn.sh` script used at the beginning of the tutorial did not properly set the environment variables `GIT_NEW_REPO_NAME` and `GIT_REPO`. I had to manually run the following to work around this issue:
    ```bash
    export GIT_NEW_REPO_NAME=keptndemo
    export GIT_REPO=https://github.com/jwenz723/keptndemo.git
    ```
2. Various pods went into a non-running status (either CrashLoopBackOff or Error). This caused the quality gates to never pass since they could not retrieve the necessary metrics for the gate.
![Screenshot_20230123_113720](https://user-images.githubusercontent.com/8587171/214227820-6753320c-e076-4835-bd54-6affdb04353c.png)

**Comment by jwenz723** [comment]
I was only able to retrieve the failure reason for 1 pod before my killercoda session expired.


`kubectl describe pod -n monitoring prometheus-prometheus-node-exporter-2z4k6`

![image](https://user-images.githubusercontent.com/8587171/214228969-b04a9707-9115-4e3d-a70f-f9bb71659648.png)

**Comment by agardnerIT** [comment]
Closing as stale. Please re-open if this is still an issue.
