### ISSUE TITLE
Document how to upload an API file to a Keptn project repo

### ISSUE THREAD

**Issue by StackScribe** [keptn/keptn.github.io#1586]
Create a new page about how to upload an API file to a Keptn project repo.  This can be done in either of two ways:

* upload it directly to your git repo
* use the resource-service API for uploading with the example snippted from above

A good location for this information is in https://keptn.sh/docs/1.0.x/reference/api/ .  You may find additional improvements you can make to this page.

Detailed source material in https://keptn.slack.com/archives/CNRCGFU3U/p1675392513863559?thread_ts=1675392236.223169&cid=CNRCGFU3U

**Comment by bhavyastar** [comment]
Hey, @StackScribe I would like to work on this issue.

**Comment by ashutosh887** [comment]
Hey @StackScribe @bhavyastar 
Is this issue still available to work on?
I can see the PR got closed once 🤔

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
