### ISSUE TITLE
docs: add issue template

### ISSUE THREAD

**Issue by bhavyastar** [keptn/keptn.github.io#1593]
-> Issue template provides ease for the folks who want to open an issue.
-> It differentiates the various types of issues such as `Code, Bugs, Docs, Enhancements and Others`
-> It also follows community standards.

**Comment by bhavyastar** [comment]
I would like to work on this issue.
cc- @DavidPHirsch @agardnerIT @bradmccoydev

**Comment by aepfli** [comment]
Can we create a general issue template that would work for all our repositories?

Maintaining those for all repositories can be pretty hard, and we usually can store them within the `.github` repository. This way, they would apply to all projects.

So ideally, we will generate one default template for all repositories and overwrite them in the repos of need. (a shameless plug with information https://engineering.dynatrace.com/blog/our-journey-to-a-streamlined-github-organization-community-health-and-other-organizational-topics/)

What do you think @bhavyastar ?

**Comment by bhavyastar** [comment]
Yup for sure @aepfli !! Good idea!

**Comment by mowies** [comment]
@bhavyastar please check the templates that we have in https://github.com/keptn/keptn as a reference

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
