### ISSUE TITLE
Addition of prerequisite for helm in website docs

### ISSUE THREAD

**Issue by SuperAayush** [keptn/keptn.github.io#1594]
Under the installation process in docs, the section of [Choose access options](https://keptn.sh/docs/install/access/) does contain the helm repo add information but directly contains the next step of helm charts installation.

A prerequisite can be added to add the helm keptn repo first before going for helm installation as discussed in today's community meeting.

The command could be: helm repo add keptn https://charts.keptn.sh

For more information visit here: https://artifacthub.io/packages/helm/keptn/keptn

cc- @DavidPHirsch @agardnerIT @bradmccoydev

**Comment by SuperAayush** [comment]
I would like to work on this!!

**Comment by SuperAayush** [comment]
Before starting to make changes I wanted to gather some thoughts regarding these two pages:
1. [Choose access options](http://localhost:1313/docs/1.0.x/install/access/)
2. [Install Keptn using the Helm chart](http://localhost:1313/docs/1.0.x/install/helm-install/)

I feel that these two pages contain pretty much the same information and content and can be merged to make a single page 🤔. Please let me know your thoughts on this and also if something else can be done.
OR
We can maybe swap the two pages which can also be a solution.

cc- @agardnerIT @DavidPHirsch

**Comment by DavidPHirsch** [comment]
I would be in favor of merging

**Comment by agardnerIT** [comment]
I agree that both these pages are conceptually very close to one another and can probably be merged.

**Comment by ashutosh887** [comment]
@SuperAayush 
If merged, let's close this issue 😄

**Comment by SuperAayush** [comment]
Hey @ashutosh887!!

There is still some work left on this issue, I am in the middle of my exams and would work on it after they are finished.
I still have some changes to make as per the suggestion of Meg and Adam.
Thank you for giving me a reminder.

**Comment by ashutosh887** [comment]
Yeah please take your time @SuperAayush 
Best of luck to you!

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
