### ISSUE TITLE
docs: add PR template

### ISSUE THREAD

**Issue by bhavyastar** [keptn/keptn.github.io#1596]
When you add a pull request template to your repository, project contributors will automatically see the template's contents in the pull request body.

For more information read this documentation -> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by iamrajiv** [comment]
@bhavyastar Will you be using default pull request templates, creating custom templates, or following templates from other organizations?

**Comment by bhavyastar** [comment]
Hey @iamrajiv, Actually In this repo there is no pull request template so it will be good to create the pull request template. 
I can create custom templates.

**Comment by YashPimple** [comment]
@bhavyastar would like to work on this issue ! can you please assign it to me

**Comment by mowies** [comment]
@bhavyastar please check the templates that we have in https://github.com/keptn/keptn as a reference

**Comment by SuperAayush** [comment]
I think regarding this in the community meeting we discussed creating a single Issue and PR template that can apply to all the Keptn repos rather than having separate templates for separate repos.

**Comment by YashPimple** [comment]
@mowies @bhavyastar any update for the above issue?

**Comment by aroramrinaal** [comment]
@bhavyastar @mowies , is this issue still open?

**Comment by mowies** [comment]
we have a PR that is mostly done but there are some requested changes to do for @YashPimple

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
