### ISSUE TITLE
In Footer section the word with the link attached to it looking lighter

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn.github.io#1639]
![keptn](https://user-images.githubusercontent.com/95420063/236910508-553bbed9-7911-4fb2-bda6-a9f33defa3de.png)
Page Link : https://keptn.sh/why-keptn/
We can make this black so it will  be visible clearly
I m working this issue

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
