### ISSUE TITLE
Bug:inside the integration part of the docs section some of the text buttons are colliding to each other

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn.github.io#1640]
### Proposal
inside the integration in docs section some of the text buttons are colliding to each other

By visiting to this page
https://keptn.sh/docs/integrations/#available-integrations
![keptn1](https://user-images.githubusercontent.com/95420063/236978669-e43bf6ee-ede9-4567-bc7f-a3081afaa8e7.png)

I m working on this issue
### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
Thanks @rakshitgondwal , you are right :) moving the issue to the right repo

**Comment by Nitishupkr** [comment]
Thank you and assign it to me.

**Comment by thisthat** [comment]
Thanks @Nitishupkr, assigned to you :)
