### ISSUE TITLE
Bug: In integration section  on clicking the security button no integration found reported

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn.github.io#1642]
explanation : in the integration section  clicking on the security button its getting broken link 
steps to visit:https://keptn.sh/docs/integrations/
![keptnnewbug](https://github.com/keptn/keptn.github.io/assets/95420063/e8303925-0ed1-4b37-a8a6-453610b622af)
I m working on this issue

**Comment by Nitishupkr** [comment]
@rakshitgondwal please check it

**Comment by rakshitgondwal** [comment]
Hey @Nitishupkr, This is because we don't have any integrations for security as of now :)
https://artifacthub.io/packages/search?kind=10&sort=relevance&ts_query_web=security

**Comment by Nitishupkr** [comment]
ok

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
