### ISSUE TITLE
[BUG] Responsiveness in footer

### ISSUE THREAD

**Issue by himanshu1221** [keptn/keptn.github.io#1647]
- I was checking the responsiveness of the website when I find out that there is a wide white gap in the footer as we can see in screenshot
 
- If this issue is relevant kindly assign me this issue I would love to fix it

![Screenshot from 2023-06-02 22-30-23(1)](https://github.com/keptn/keptn.github.io/assets/32031706/b48b1ce8-67a7-4627-bd0c-7aa5940d121d)

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
