### ISSUE TITLE
[BUG] v1 docs CSS missing

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn.github.io#1648]
The docs are returning a 404 for the `/css/style.min.c4db12f74faef69e28efd1fea384bb0dcdd9d3daf7a9a66c158914ef0cc56234.css` path.

Impact: Website is rendered incorrectly.

<img width="568" alt="image" src="https://github.com/keptn/keptn.github.io/assets/26523841/9d6322f6-a95c-400c-84cb-9616891b4fa3">

<img width="1901" alt="image" src="https://github.com/keptn/keptn.github.io/assets/26523841/4cc08afc-c78d-403f-8542-b2955a1469e6">

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
