### ISSUE TITLE
the readmore buttons are not aligned in the same order

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn.github.io#1650]
the read more buttons are not aligned  properly which looks odd in the ui
before:
![image](https://github.com/keptn/keptn.github.io/assets/95420063/b8e7e4c9-5f54-4f5b-adf1-ba1e076af29f)
after:
![image](https://github.com/keptn/keptn.github.io/assets/95420063/ecdeb1b3-30d3-4dd9-b3b9-c2ece3e28c46)
i will solve this issue

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
