### ISSUE TITLE
update happy-users.html

### ISSUE THREAD

**Issue by Nitishupkr** [keptn/keptn.github.io#1651]
![asdfg](https://github.com/keptn/keptn.github.io/assets/95420063/1d3e112f-9966-43ca-9937-e14a264adca2)
I m not sure about this check it once whether it is wrong or not.

**Comment by promise-dash** [comment]
I guess it should be "flawlessly". 
I can resolve this typo. 
Could you please assign me this?

**Comment by Nitishupkr** [comment]
Thanks for the interest but 
I've done it, but the only thing left to do is rise PR.

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
