### ISSUE TITLE
Supported versions table is outdated

### ISSUE THREAD

**Issue by shazib-summar** [keptn/keptn.github.io#1656]
**Is your feature request related to a problem? Please describe.**
The supported versions table at [this link](https://keptn.sh/docs/install/k8s-support/#supported-versions) shows the table for version `0.18.x` and `0.19.x` even when newer releases have been published.

**Describe the solution you'd like**
The table/page should be updated in regards to the new versions that have been published.

**Describe alternatives you've considered**
None

**Additional context**

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/27294025/215516411-a0ebc193-7133-44c3-a781-eeed3fd32e0b.png">

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
