### ISSUE TITLE
Footer is not responding properly when reloaded

### ISSUE THREAD

**Issue by nihalpawar4** [keptn/keptn.github.io#1657]

**Comment by nihalpawar4** [comment]
assign me the issue, would love to contribute on this

**Comment by rakshitgondwal** [comment]
@nihalpawar4 Can you please provide a screenshot of the error you are facing, also please confirm if you're referring to https://lifecycle.keptn.sh/ or https://v1.keptn.sh/

**Comment by StackScribe** [comment]
Keptn V1 has reached EOL on December 22nd, 2023, so this issue has been closed.
