### ISSUE TITLE
Create end-to-end tutorial for developers

### ISSUE THREAD

**Issue by kostis-codefresh** [keptn/keptn.github.io#199]
The current keptn documentation is missing a very critical item. An end-to-end tutorial for developers that explains how to use keptn.

Let's say that I am a developer and I already have a cluster with keptn installed. I also have an application with a simple dockerfile. What should I do next in order to use keptn?

**Comment by grabnerandi** [comment]
In the doc we have a section on Use Cases. This is a step-by-step tutorial on e.g: onbaording a service, running a delivery, self-healing ... -> https://keptn.sh/docs/0.3.0/usecases/
Is this what you are looking for?

**Comment by kostis-codefresh** [comment]
@grabnerandi This starts from an existing project. What if I have a brand new project? Let's say only a dockerfile and source code. Is that enough? What are the possible values for shipyard.yaml? Do I also need another file apart from shipyard.yaml? What if I am using plain K8s manifests and not Helm? Will that work?

Basically what are the requirements for a project to be keptn ready? i.e. a hello-world from start to finish.

**Comment by grabnerandi** [comment]
Understood. Our team is currently working on additonal blog posts on how to onbaord your custom services. We will make sure to highlight what the starting point of a keptn project is.
#1: keptn needs you to specify a shipyard file (your project) and then onboard your services -> as described here: https://keptn.sh/docs/0.3.0/usecases/onboard-carts-service/
#2:  keptn DOESNT build -> keptn requires an artifact already available in e.g: a docker registry. So - you would use some CI tool to build an artifact and push it to a registry. Once you have an artifact you would  tell keptn that there is a new artifact, e.g: through the keptn cli as explained here: https://keptn.sh/docs/0.3.0/usecases/onboard-carts-service/#send-a-new-artifact-and-watch-keptn-doing-the-deployment

**Comment by AloisReitbauer** [comment]
@kostis-codefresh on a different note: Would codefresh be interested in collaborating around standardized application lifecycle events as we started to define in https://github.com/keptn/keptn-specification/blob/master/cloudevents.md

**Comment by danielkhan** [comment]
https://github.com/keptn/keptn.github.io/pull/235 addresses this. Closing.
