### ISSUE TITLE
It would be good in have a page in keptn.sh that list the available "adapters/connectors" that Keptn support integrating

### ISSUE THREAD

**Issue by vinsontan** [keptn/keptn.github.io#393]
It would be great to enhance the keptn.sh web site to include a page that list out the list of available adapters/connectors that integrate with keptn. I find it difficult to find it without knowing it was in the github.com/keptn-contrib.

**Comment by johannes-b** [comment]
Hi, thanks for this PR and your suggestion to list available adapters. I will take care of creating this support page.

**Comment by christian-kreuzberger-dtx** [comment]
I'd like to go even one step further and state that we need a list of (official) contributions and with which Keptn version they are compatible.
