### ISSUE TITLE
Duplicate logos in "Get in touch!" section

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn.github.io#404]
The "Get in touch!" section contains duplicate logos. They should be removed.

![Screen Shot 2020-01-09 at 13 01 22](https://user-images.githubusercontent.com/10980861/72066213-4c286400-32e0-11ea-86db-dfdaa1174bd3.png)

**Comment by jetzlstorfer** [comment]
fixed in PR #403

**Comment by johannes-b** [comment]
This issue has been resolved. Thanks!
