### ISSUE TITLE
Clarify Docs

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn.github.io#436]
Please clarify this paragraph:

> Note: A basic health-check (i.e., accessing `/health` of the carts-service) is always triggered before the functional and performance tests are executed. This means, that if a basiccheck.jmx file is available, it will be executed first. The reason is that performance tests should not be executed if a basic health check fails.

I read this as: "A single request to `/health` is always performed, regardless of any functional or performance tests. _Then_ any functional or performance tests are executed (if they're present)."

The following line then contradicts this by mentioning an added resource. What if there is no added resource? Is the `/health` endpoint triggered in that case?

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

this note has been modified in PR https://github.com/keptn/keptn.github.io/pull/391 a couple weeks ago.

@johannes-b and @jetzlstorfer can you please double-check if the statement is contradicting/unclear?

**Comment by johannes-b** [comment]
Thanks for the hint. After re-reading the lines, I realized that this paragraph is confusing. 
My suggestion (as implemented in the jmeter-service):

**Note:** A basic health check - as implemented in the `basiccheck.jmx` file - is always performed regardless of any functional or performance tests. This is conducted to validate the availability of the service that will be tested. If the basic health check passes, either the functional or performance tests are executed depending on the shipyard configuration.

@jetzlstorfer - May I ask you for feedback on my suggestion? I can then file a PR for that issue.

**Comment by jetzlstorfer** [comment]
I think it is definitely an improvment. Giving this another thought, however, we could even get rid of the term "basic health check" because we don't really know what the `basiccheck.jmx` is all about, it can be more than a basic health check.

My suggestion:
**Note**: To validate the availability of the service that will be tested, the `basiccheck.jmx` is always executed _before_ the `load.jmx` gets executed. Therefore, if performance tests should be executed, a `basiccheck.jmx` also has to be available.

@johannes-b - what do you think? Does this make it more clear?

**Comment by Dynatrace-Adam-Gardner** [comment]
Am I also correct in thinking the path: `--resource=jmeter/basiccheck.jmx` is hardcoded so the basic check file must always be called `basiccheck.jmx`? Same with `load.jmx`? If so, we should specify that more clearly in the docs. I can see people calling these files whatever they wish.

**Comment by jetzlstorfer** [comment]
yes, you are right.

**Comment by johannes-b** [comment]
@jetzlstorfer your suggestion makes it now clear and I added @Dynatrace-Adam-Gardner 's hint regarding the file name: 

I would update it to: 
**Note 1:**  To validate the availability of the service that will be tested, the `basiccheck.jmx` is always executed before the `load.jmx` gets executed. Therefore, if performance tests should be executed, a `basiccheck.jmx` also has to be available.

**Note 2:** You can adapt the `basiccheck.jmx` or `load.jmx` tests for your service but do not rename the files. In the current implementation of Keptn's jmeter-service, there is a hardcoded dependency on these file names.

**Comment by johannes-b** [comment]
PR #443 has been approved and merged. Again, thanks for the feedback!
