### ISSUE TITLE
Update Screenshots for Keptn's Bridge in 0.6.x docs

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#448]
- Update all appearances of Keptn's Bridge with appropriate screenshots
- Also fix the typo on the title of this pic: https://keptn.sh/docs/0.6.0/usecases/deployments-with-quality-gates/assets/quality_gates.png

**Comment by agrimmer** [comment]
I will update the screenshot of the Bridge in https://deploy-preview-461--keptn.netlify.com/docs/0.6.0/usecases/self-healing-with-keptn/prometheus-scaling/

**Comment by johannes-b** [comment]
The screenshot are updated.
