### ISSUE TITLE
Reorganize "Get started" section into "Concepts" section

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#488]
Everything that is currently situated in the **Get started** section:
![Screenshot from 2020-03-30 18-50-37](https://user-images.githubusercontent.com/56065213/77939392-635f6800-72b7-11ea-8d23-a2c4c1e1f0b5.png)
should be moved into a release-independent section.

As a proposal, we could call it "A brief introduction to Keptn" with a reference to its core principles.

**Comment by johannes-b** [comment]
The agreed approach for addressing this issue is that a section called **Concepts** should show the following content:
![image](https://user-images.githubusercontent.com/729071/79988860-70830780-84af-11ea-922f-32392c0bb0ba.png)
