### ISSUE TITLE
Document "expose keptn's bridge" story in Bridge Reference document

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#506]
Right now the command is only documented in the (auto-generated) CLI docs.

We should also document the behaviour including the step with basic authentication here:
https://keptn.sh/docs/develop/reference/keptnsbridge/

**Comment by johannes-b** [comment]
The PR https://github.com/keptn/keptn.github.io/pull/521/ contains the documentation for `keptn configure bridge` including docu for enabling/disabling basic authentication.

When the PR is merged into master, I will take care of adding the documentation also to the "develop" folder.
