### ISSUE TITLE
Add a "we work with your tooling" panel

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn.github.io#516]
A core strength of Keptn is that it integrates with almost any external tool. The Keptn homepage should highlight this.

A section that shows logos for integrations currently built. This could be a static graphic, but better would be a section that is dynamically built from logos placed into a certain directory.

For example:
![keptn-integrations](https://user-images.githubusercontent.com/13639658/80171238-2758c200-862d-11ea-8c9e-baf1348f8283.png)

**Comment by johannes-b** [comment]
Great idea! We are currently reworking the keptn/docs (since the tutorials have been moved to tutorials.keptn.sh). In course of that rework, I will add this image to the *Integrations* page.

**Comment by Dynatrace-Adam-Gardner** [comment]
Please don't add this image. It isn't organised, consistent and looks terrible :)

**Comment by jetzlstorfer** [comment]
Hi @Dynatrace-Adam-Gardner ,
we have updated the Keptn.sh website and it now includes the list of tools that Keptn is integrating with.
![image](https://user-images.githubusercontent.com/7677092/108320133-acb3f100-71c2-11eb-85a6-b64b7fda6014.png)

Plus, we added an integrations page that list some of them in more detail. https://keptn.sh/docs/integrations/ 

What do you think? Does this address the issue?

**Comment by jetzlstorfer** [comment]
No further activity, closing this issue.
