### ISSUE TITLE
Fix writing of keptn CLI to use a lowercase k in docs

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#525]
There are several occurances of Keptn CLI in the docs, which need to be changed to a lowercase k.

Please note, that the docs for the actual CLI (see *content/docs/develop/cli/commands*) are auto-generated, they need to be fixed in https://github.com/keptn/keptn/issues/1718

**Comment by johannes-b** [comment]
This has been done.
