### ISSUE TITLE
Update develop docs: Keptn configure bridge now contains --user and --password

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#569]
Reported by @ermin-muratovic 

In the develop docs we need to adapt the `keptn configure bridge` command to always include `--user` and `--password`.

According to @bacherfl this has been done already (but maybe not on all occurances)

**Comment by christian-kreuzberger-dtx** [comment]
Please wait before adapting this, as if we implement KEP 18 there will be some additional changes.

**Comment by johannes-b** [comment]
This can be closed due to the changes from KEP 18.
