### ISSUE TITLE
Documentation of required PersistentVolumeClaim 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#587]
Explain the purpose of the following to PVS: 
- configuration-volume: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L487
- mongodata: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/charts/mongodb/templates/pvc.yaml

Also provide a recommendation of their size. 

**Definition of Done:**
- [ ] PVS and size recommendation is explained

**Comment by agardnerIT** [comment]
Is this still relevant or can it be closed?

**Comment by DavidPHirsch** [comment]
closing as issue is stale
