### ISSUE TITLE
Explain requirements for execution plane services in the dev docs

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#633]
Each service in the execution plane has to fulfill the same requirements. This should be explained for developers.

*Content:*
- https://keptn.sh/docs/0.7.x/integrations/custom_integration/
- https://keptn.sh/docs/0.7.x/integrations/sli_provider/
- https://keptn.sh/docs/0.7.x/integrations/action_provider/ 

**Tasks:**
- The service has to listen for POST requests (default on port 8080).
- The service has to send a task.started as well as a task.finished event to the public API of keptn
- Extend docs with an architecture diagram
- Extend developer docs for external contributions (incl. deployment template for the sidecar)

**Definition of Done:**
- [ ] An external contributor can write a Keptn-service running in the execution-plane, which adheres to all requirements

**Comment by agrimmer** [comment]
You are right that all execution plane services have to send a `task.started` and `task.finished` event. Fortunately, if a service uses the provided `distributor`, the distributor will handle the communication to NATS/the public API. 
That means a service can simply post an event on 127.0.0.1:8081 and the distributor forwards the event to NATS/the public API.
