### ISSUE TITLE
Separate Download Page for Keptn CLI

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#645]
In https://github.com/keptn/keptn/issues/2293 we print the user a message where to download the latest Keptn CLI version (via a pre-defined link structure, e.g., https://keptn.sh/docs/${version}/operate/upgrade ).

While this URL might change in the future, I also believe that a download link is something that should not be hidden in a subsection of the docs, but should be visible on a separate download page, e.g., https://keptn.sh/download or maybe even as a page on https://get.keptn.sh.

This page could look as follows:
* Preferred (Linux, MacOS): `curl -sL https://get.keptn.sh | sudo -E bash` or specify a version using `curl -sL https://get.keptn.sh | sudo -E KEPTN_VERSION=0.7.2 bash`
* Manually Download Keptn CLI from GitHub
  * Latest: 0.7.2 - ReleaseNotes, Docs / Download: Windows, Linux, MacOS
  * 0.7.1 - ReleaseNotes, Docs / Download: Windows, Linux, MacOS
  * 0.7.0 - ...
  * 0.6.2 - ReleaseNotes, Docs / Download: Windows, Linux, MacOS
  * 0.6.1 - ...
  * 0.6.0 - ...

We also should add a link to the downloads page in the top menu. Within the docs, instead of referencing to github.com/keptn/keptn/releases we should reference to keptn.sh/downloads (or get.keptn.sh)

As an alternative, we could look into always referencing our [Quickstart Guide](https://keptn.sh/docs/quickstart/#2-1-install-keptn-cli) - this is basically what Istio and Helm are doing.

**Comment by DavidPHirsch** [comment]
connected PRs are closed
