### ISSUE TITLE
Remove "Keptn on microk8s" docs

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#648]
In my opinion, the docs regarding [Installing Keptn on Microk8s](https://keptn.sh/docs/0.7.x/operate/microk8s/) are misplaced for multiple reasons.

1. This does not have anything to do with "Operating Keptn", but it's more about "how to setup Microk8s" (on MacOS and Ubuntu).
2. Our installation instructions provide several different options (e.g., for K3s, Minikube, GKE, ...) - but not for Microk8s.

The following instructions should really be all that's needed (from Keptn core perspective):

```console
sudo snap install microk8s --classic
sudo iptables -P FORWARD ACCEPT
sudo microk8s.enable dns
sudo microk8s.enable dns ingress
sudo microk8s.enable storage
sudo /snap/bin/microk8s.config > kubeconfig
export KUBECONFIG=./kubeconfig
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
```

followed by
```console
keptn install ...
```

# Suggestion

- [ ] Remove https://keptn.sh/docs/0.7.x/operate/microk8s/ for 0.7.x and 0.8.x
- [ ] Add simple instructions (see above) into https://keptn.sh/docs/0.7.x/operate/install/ for 0.7.x and 0.8.x

**Comment by johannes-b** [comment]
Like the proposed idea since it reduces the menu items under "Operate Keptn".

**Comment by christian-kreuzberger-dtx** [comment]
This has already been done for 0.8.x.
I don't see a reason to touch the docs for 0.7.x as it has already been deprecated.
