### ISSUE TITLE
Document migration path for integrations from Keptn 0.7.x to Keptn 0.8.x

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#690]
We need to document possible breaking changes that need a migration path for 3rd-party services (e.g., keptn-in-a-box, azure devops pipelines, gitlab ci, bitbucket, alexa-service, ...).

This affects
 
a) external services that connect to the API, and
b) Keptn-services that use go-utils and Keptn CloudEvents.

I've added some insights in those things in the issue here, so we can work from that. In the end, this should be a separate page in the docs, e.g., a sub-page called "Migrating from 0.7.x to 0.8.x" here https://keptn.sh/docs/0.8.x/integrations/ 

# Affected Things

## External Services / Integrations (affected breaking changes in public Keptn API or CLI)

Potentially affected services/contributions:

* keptn-in-a-box
* azure devops pipelines
* bitbucket / gitlab ci pipelines

## Keptn-services / Cloud-Events

* every service that was built using keptn-service-template-go
* every service that uses go-utils
* sli-providers
* remediation-providers
* several other services that are not using go-utils and have been custom-built, e.g., [notification-service](https://github.com/keptn-contrib/notification-service), [neoload-service](https://github.com/keptn-contrib/neoload-service), ... (here we can only provide general guidance of how CloudEvents and API have changed)

# First insights
I am providing first insights here. They are mostly based on my PR on [keptn-sandbox/keptn-service-template-go](https://github.com/keptn-sandbox/keptn-service-template-go/pull/24) and should provide a good base on what needs to be changed.

## Keptn Public API Changes

* Introduction of shipyard controller API via `/api/controlPlane/v1`
* Adding and updating resources now works via the following endpoitns: **TODO**
* Project Endpoints have been moved to: **TODO**
* Stage Endpoints have been moved to: **TODO**
* Service Endpoints have been moved to: **TODO**
* Evaluation (start-evaluation) Endpoint has been moved to: **TODO**
* Get-Events Endpoint has been moved to: **TODO**
* **TODO**: Please list all breaking changes for end-users/devs

## Keptn CLI Changes

The Keptn CLI has been updated to use the latest CloudEvents spec 0.2.0. This required some changes in the CLI, most notably

- Evaluations are no longer triggered using `keptn send event`, but using `keptn trigger evaluation` (e.g., `keptn trigger evaluation --project=my-sockshop --service=foobar --stage=hardening`)
- Sending a configuration-change/new-artifact is no longer triggered using `keptn send event`, but using `kept trigger delivery` (e.g., `keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo --tag=4.2.2 --sequence=delivery-direct`)
- **TODO** Any more changes **important** and **breaking** changes? Please add them!

# Definition of Done

- [ ] Provide a changelog of breaking changes in the public Keptn API
- [ ] Provide a changelog of breaking changes in the Keptn CLI
- [x] Provide a migration guide for changes related to go-utils and keptn-service-template-go
- [x] Provide a migration guide for sli-providers
- [x] Provide a migration guide for remediation-providers
- [x] Provide guidance about changes in CloudEvents (e.g., react on `.triggered` events, send `.started` and `.finished` events)
- [x] Provide guidance about changes in the workflow/sequence, e.g., if you listened to `tests-finished` before, you should now listen to `deployment.triggered`
- [x] Provide information about relevant changes in the `distributor` (e.g., use version `0.8.0-alpha`, resource requests/limits, etc...)

**Comment by johannes-b** [comment]
Awesome work! This issue is a very comprehensive overview of what has changed for 0.8 in regard to building integrations. 

Maybe just a short note, the manifest of the distributor has changed in the meantime. Please see: https://keptn.sh/docs/0.8.x/integrations/custom_integration/#subscription-to-keptn-event

**Comment by christian-kreuzberger-dtx** [comment]
My PR #755 is showing the current state of the migration guide at https://deploy-preview-755--keptn.netlify.app/docs/0.8.x/integrations/migrate_from_070_to_080/

I have not yet had time to add the guide regarding api and cli changes.
