### ISSUE TITLE
Provide search for Keptn docs

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn.github.io#693]
Feedback from the community: there is a search box needed for the docs.
Right now there is a lot of "domain knowledge" needed to find the things you are looking for.

A search box would help a lot.

**Comment by oleg-nenashev** [comment]
FTR there are searches like Algolia which can be sponsored for open source projects. There search engine also allows multi-site indexing that is important for Keptn (e.g. main website and tutorials are on separate subdomains)

**Comment by jetzlstorfer** [comment]
Thanks Oleg for this suggestion. I'm linking the landing page here for further reference https://www.algolia.com/for-open-source/ 
This is something we should consider.

**Comment by DavidPHirsch** [comment]
connected PR is closed
