### ISSUE TITLE
Provide docs for auto-completion feature in CLI

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn.github.io#729]
Similar to https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion we need a documentation on how to use the auto-completion feature in the CLI.

Currently, it is not clear how to use it, as e.g., this issue shows: https://github.com/keptn/keptn/issues/3212

**Comment by jetzlstorfer** [comment]
Maybe @DarthBenro008 can help here?

**Comment by DarthBenro008** [comment]
Hey @jetzlstorfer,
Sure! we definitely need documentation to enable autocompletion.

I can help out in documenting the relevant section, however could you please point out where exactly to add the this section in the website?

**Comment by jetzlstorfer** [comment]
Thanks @DarthBenro008 !
I guess this would be the best place https://keptn.sh/docs/0.8.x/reference/cli/
