### ISSUE TITLE
Provide docs for deprecated Keptn versions

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn.github.io#747]
The docs for deprecated Keptn versions (currently < 0.6.x) are currently not rendered and that might break some older links that are out there on the interwebs. 
We should still render these docs but not link them in the docs section anymore. 

In the `config.toml` we should remove the ignored files, but need to find a way to hide them from the menu in the *docs* section of the website.

**Comment by DavidPHirsch** [comment]
stale
