### ISSUE TITLE
Make sure auto-generated files are not commited to git

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#761]
As discussed in https://github.com/keptn/keptn.github.io/pull/758, we often have files in resources/_gen/ folder in our PRs.

That's certainly not what we want, as they are autogenerated.

# Definition of Done
- [ ] Auto-generated css/js/html/... files are no longer part of PRs
- [ ] Website and netlify deploy still works as expected

**Comment by christian-kreuzberger-dtx** [comment]
FYI @DarthBenro008

**Comment by DarthBenro008** [comment]
Would like to work on this! Could you please assign me this issue?

**Comment by christian-kreuzberger-dtx** [comment]
FYI @jetzlstorfer please also take a look at this
