### ISSUE TITLE
Installing helm-service and jmeter-service manually

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#770]
As we can see in https://keptn.sh/docs/0.8.x/operate/multi_cluster/ it is possible to install helm-service and jmeter-service on another cluster (or within the same cluster in a separate namespace).

However, I wanted to point out that it is also possible to deploy helm-service and jmeter-service directly using a helm-chart, if deployed into the same namespace:

```console
keptn install -n keptn # without --use-case=continuous-delivery
helm install jmeter-service https://github.com/keptn/keptn/releases/download/0.8.0/jmeter-service-0.8.0.tgz -n keptn
helm install helm-service https://github.com/keptn/keptn/releases/download/0.8.0/helm-service-0.8.0.tgz -n keptn
```

Other variants are also possible, e.g., just installing keptn control plane + jmeter-service (without helm-service)

# Definition of Done
- [ ] The above mentioned installation method is documented on keptn.sh/docs

**Comment by DavidPHirsch** [comment]
stale
