### ISSUE TITLE
Multi-cluster installation: Provide better guidance for helm + jmeter (not just jmeter)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#800]
Right now in our [multi-cluster setup documentation](https://keptn.sh/docs/0.8.x/operate/multi_cluster/), we only provide specific guidance for installing jmeter-service via a helm chart.
However, I believe that we should also provide guidance on how to install helm-service.

Example:
See https://github.com/keptn/keptn.github.io/issues/770

# User Story

As a user, I want to copy paste commands for installing helm-service and jmeter-service as a (remote) execution plane service.

# Definition of Done

- [ ] [multi-cluster setup docs](https://keptn.sh/docs/0.8.x/operate/multi_cluster/) are restructured in a generic/configuration part, and an installation part
- [ ] multi-cluster setup docs contain instructions that can be copy pasted for installing and uninstalling helm-service and jmeter-service

**Comment by DavidPHirsch** [comment]
stale
