### ISSUE TITLE
Improve shipyard examples / expanding examples

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#808]
When scrolling through our shipyard examples, I encountered a visual problem:

![image](https://user-images.githubusercontent.com/56065213/117780040-880a6b00-b23f-11eb-9129-37fccf70f5a4.png)

I was able to immediately see the 4 lines of code for an approval task, but I did not see the "**Example**: Extend shipyard ... " text at the bottom at first.

In my opinion, the text is too far away from the example. I believe that we can improve this, by moving the text closer to the code box, a little bit to the right to align with the code box, and changing the wording a bit, e.g.:

![image](https://user-images.githubusercontent.com/56065213/117781185-a4f36e00-b240-11eb-9520-317f2a71e97d.png)

**Comment by DavidPHirsch** [comment]
outdated
