### ISSUE TITLE
Add Docs: How to communicate with the distributor? How to send a proper CloudEvent?

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn.github.io#828]
While writing https://github.com/ChristianKreuzberger/keptn-service-template-python I had some issues with sending CloudEvents back to Keptn (via the Distributor).

I used the documentation provided here: https://keptn.sh/docs/0.8.x/integrations/custom_integration/#send-a-started-event

![image](https://user-images.githubusercontent.com/56065213/119819451-af745f80-bef0-11eb-9d67-92b6cd6ec2f1.png)

Option 1 does not work for me, as I am running within the Keptn Kubernetes Cluster and I want to communicate via the distributor.
Option 2 does not work either, as sending the CloudEvent to  127.0.0.1:8081 did not work. I had to send it to `http://127.0.0.1:8081/event` (please mind the protocol `http`, and the path `/event`!)

Furthermore, it was really really troublesome in creating a CloudEvent that would eventually be mapped to the correct sequence in Keptn:

1. It needs to have the correct `shkeptncontext`
2. It needs to have the correct `triggeredid`
3. It needs to have the correct `data.project`, `data.stage` and `data.service` properties set

I believe these things might be addressed in the [Keptn spec / CloudEvents](https://github.com/keptn/spec/blob/master/cloudevents.md), but we should add a note about that so future devs have a reference.

Anyway, one more problem occurred (and that's part of Keptn Core): In case I miss any of these attributes, I will not get an error message or anything else, I'm just lost and I have to do some reverse engineering (I actually had to look at the distributor Source Code). This should be reasoning enough to provide a better documentation.

# Proposal

- [ ] Change the custom integration docs to provide the proper URL for sending CloudEvents via the Distributor
- [ ] Add a separate page about the distributor, and which endpoints it provides (reference to existing Swagger UIs if possible)
- [ ] Add a note to show which parts of a CloudEvent are required for Keptn to map it, link to spec for more details
- [ ] Describe error log propagation via distributor as well (general-purpose cloudevents)

**Comment by DavidPHirsch** [comment]
outdated
