### ISSUE TITLE
Explain remediation sequence and show example how to trigger it

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn.github.io#829]
### User story

As a user, I would like to understand how the looping mechanism of the proposed remediation sequence is working and what it actually means: https://keptn.sh/docs/0.8.x/automated_operations/remediation/#declare-a-remediation-sequence-in-shipyard

Besides, I would like to get an example of how to trigger the sequence and an explanation which service (dynatrace-service, prometheus-service) are doing this automatically.

#### Aceptnance criteria

- [ ] I can understand how the looping is done
- [ ] A example is given to trigger a remediation sequence for testing purpose

#### Definition of Done 

- [ ] Docu is updated here https://keptn.sh/docs/0.8.x/automated_operations/remediation/#declare-a-remediation-sequence-in-shipyard
- [ ] Example for triggering a rem. sequence is provided at this page: https://keptn.sh/docs/0.8.x/automated_operations/remediation/#title

**Comment by DavidPHirsch** [comment]
outdated
