### ISSUE TITLE
Quick Start guide fails if helm is not installed

### ISSUE THREAD

**Issue by DarthBenro008** [keptn/keptn.github.io#843]
The new quick start that was revamped in #826 is really great! However, i tried blindly following the quick-start and realized the demo failed to execute because I did not have `helm` installed locally into the dev env.

**How to reproduce the bug?**

- Follow the tutorial at https://keptn.sh/docs/quickstart/ and install the optional demo without helm installed locally

![image](https://user-images.githubusercontent.com/31009634/122469838-62cdf280-cf8b-11eb-8574-a040f1baefeb.png)

**Output:** 

![image](https://user-images.githubusercontent.com/31009634/122469660-3619db00-cf8b-11eb-94ca-90d4f3745b4c.png)

**Expected Results:**
- Demo to install without any errors

**Possible solutions:**
- Add a line in the docs to make sure the user has helm installed as a pre-requisite
- Check helm and install it within the script itself 

I personally think we should notify the user to install helm as a per-requisite. I would be happy to raise a PR regarding the same :smiley:

**Comment by christian-kreuzberger-dtx** [comment]
It says that in the pre-reqs :) 
![image](https://user-images.githubusercontent.com/56065213/122560074-6d968f00-d040-11eb-9d05-cf76429dae1d.png)

Nevertheless, feel free to raise a PR for the script in Step 5 to check for `helm` ;)

**Comment by DarthBenro008** [comment]
Oops :see_no_evil: , I must have slipped my coffee breaks. Sorry for bothering with something so silly, will surely raise a PR for script in Step 5 to check for helm!
