### ISSUE TITLE
QuickStart guide does not include minimum tool versions

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#856]
https://keptn.sh/docs/quickstart/#prerequisites documents the required tools but not their versions. When running on an old environment like my personal laptop. it may lead to strange issues caused by version incompatibility. These issues issues might make users to get lost and do not complete the quick start.

For example, in my case I had ancient kubectl on my machine, and the Istio setup failed with weird error. 

```
---------------------------------------------------------------------
Installing Istio
---------------------------------------------------------------------

./istio-1.10.0/bin/istioctl install -y
✔ Istio core installed                                                                                       
✔ Istiod installed                                                                                           
✔ Ingress gateways installed                                                                                 
✔ Installation complete                                                                                      Thank you for installing Istio 1.10.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/KjkrDnMPByq7akrYARemoving downloaded Istio resources

---------------------------------------------------------------------
Configuring Ingress for your local installation
---------------------------------------------------------------------

Error from server (NotFound): the server could not find the requested resource
```

## Suggested fixes

* Document the required versions for Docker, Kubectl, and Helm
* Nice2have: Create a simple prerequisite validator/advisor tool so that users can quickly verify their environment

## Screenshots

![image](https://user-images.githubusercontent.com/3000480/124388126-b48fb000-dce1-11eb-86a1-3d49c274c912.png)

**Comment by jetzlstorfer** [comment]
Thanks @oleg-nenashev - very nice suggestion! 
As I don't know the minimum required versions by heart this needs a bit of investigation. If you have any experience with "ancient" version that have worked for you please let us know and we can add them to the docs.

**Comment by StackScribe** [comment]
* I love the idea of the prerequisite validator/advisor tool.  This would ease pain for tutorials as well as production installations
* We should definitely document the version requirements for all ancillary software but it should be a single listing in the main installation documentation (just as the k8s version requirements are) and referenced from other docs as required.

**Comment by DavidPHirsch** [comment]
outdated as we moved to KLT
