### ISSUE TITLE
Missing Quick Start for Windows local evaluation

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#857]
Windows is a quite popular OS in enterprises, and Windows users may want to try out Keptn locally. Currently https://keptn.sh/docs/quickstart/ provides guidelines only for K3s, and they also include bash-only scripts.

Windows users cannot use K3s until https://github.com/k3s-io/k3s/issues/114 is fixed, but they can use other Kubernetes implementations like Minikube or Docker for Windows. It would be nice to create a quick start for such implementation(s), maybe with Powershell scripts.

**Comment by jetzlstorfer** [comment]
Correct. We focussed on Linux/MacOS as the WSL(2) provides support for bash scripts as well and with this it is also possible to run it on Windows systems :)

**Comment by StackScribe** [comment]
I do like the idea of a separate "Quick Start" for installing a study/demo version of Keptn on Windows, whatever our solution -- and no reason to not provide options.  Ideally, this quick start should be accompanied by videos that go through the steps in order, with commentary.

Ideally, this doc should not include any of the Keptn "exercises" for setting up quality gates, remediation, et cetera -- not sure if that is feasible.

**Comment by agardnerIT** [comment]
Closing as stale
