### ISSUE TITLE
Chore: Add issue templates to the repository

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#858]
It would be nice to have issue templates so that Keptn users/evaluators can easily report defects and feature requests for the documentation.

For example, in Jenkins we are using the following templates for jenkins.io: https://github.com/jenkins-infra/jenkins.io/tree/master/.github/ISSUE_TEMPLATE . Everything except "2-wiki-migration" could be relevant for Keptn. Note that it allows redirecting users to chats and other channels through metadata

## Sample UX for the new issue creation UI

New issue dialog:

![image](https://user-images.githubusercontent.com/3000480/124388538-ae023800-dce3-11eb-8062-de12e7e5ef0a.png)

Issue with a predefined template: 

![image](https://user-images.githubusercontent.com/3000480/124388578-cb370680-dce3-11eb-816c-12351a95a733.png)

**Comment by agardnerIT** [comment]
This was merged but I no longer see them on the `master` branch. Should we re-introduce these issue templates?

https://github.com/keptn/keptn.github.io/pull/1124
