### ISSUE TITLE
Feat: Add support for "Improve this page" and "Report issue" shortcuts

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#859]
In jenkins.io we offer links that help users to quickly report issues or suggest fixes in the documentation. It has proven to be handy for pages and small patches. We keep issues in the footer, but Keptn could do better and add some JavaScript that provides a popup with a suggest fix / report issue.

Suggested behavior:

* "Improve this page" link opens GitHub editor for the page containing content. Any user with GitHub account will be able to edit the page, preview changes, and submit a pull request in a few clicks
* "Report issue" opens a new issue GitHub dialog with the issue report template (see #858 for the templates suggestions)

## Sample screenshot

See the footer:

![image](https://user-images.githubusercontent.com/3000480/124388730-629c5980-dce4-11eb-8724-351aacf47000.png)

**Comment by DavidPHirsch** [comment]
connected PR is closed
