### ISSUE TITLE
Contributor Experience: Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#862]
Contributing guidelines are provided in https://github.com/keptn/keptn.github.io/blob/master/README.md, but this location is not automatically displayed for newcomer contributors. It would help to improve the experience for newcomer documentation contributors.

**Comment by jetzlstorfer** [comment]
Hi @oleg-nenashev 
we maintain the contributing guidelines in the main Keptn repo - https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md 
does this help?

**Comment by oleg-nenashev** [comment]
Yes and no. There are specific documentation contribution cases, and they
could be documented better
