### ISSUE TITLE
Provide a cookie consent banner

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn.github.io#947]
Since the Keptn website makes use of cookies, a cookie consent banner should be included to inform the user and ask for consent.

Here is one example 
![image](https://user-images.githubusercontent.com/7677092/137485679-309b932c-13eb-49ba-9863-688aaeb25d14.png)

Another example
![image](https://user-images.githubusercontent.com/7677092/137485811-437dcdaa-347d-4dcb-a8a3-904c6929a869.png)

**Comment by Biki-das** [comment]
this is good stuff let me try.

**Comment by DavidPHirsch** [comment]
stale
