### ISSUE TITLE
OpenGraph images are missing for Documentation

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#975]
If you put a link like https://keptn.sh/docs/quickstart/ to social media, the Keptn image would not be embedded into the post automatically. It would be great to make it possible.

More about opengraph: https://ahrefs.com/blog/open-graph-meta-tags/
There is support in hugo for it

**Comment by Nawaz027** [comment]
Hey @oleg-nenashev , I want to work on this issue.

**Comment by DavidPHirsch** [comment]
stale
