### ISSUE TITLE
Link contributor guidelines for donating new integrations to the community

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#981]
We have the new service/component onboarding guidelines here https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md#how-to-contribute-new-content . Unfortunately they are not linked from the website.

I would expect the following:

* Guildelines are updated and moved to https://keptn.sh/community/contributing/
* https://keptn.sh/docs/integrations/#contributing references the guidelines

**Comment by StackScribe** [comment]
Should we also be integrating/mapping the CONTRIBUTING.md file for keptn.github.io as part of this effort?  I want to add some information about the doc file structure to the keptn.github.io file.  Or maybe I should make that a separate issue?

**Comment by oleg-nenashev** [comment]
I think it is another issue to tackle separately. Still important

**Comment by DavidPHirsch** [comment]
stale
