### ISSUE TITLE
Link refers to the absent page

### ISSUE THREAD

**Issue by gecube** [keptn/keptn.github.io#991]
Hello!

When I click the button "Read docs" on the site, it leads to the page https://keptn.sh/docs/0.7.x/monitoring/ which is missing
![](https://habrastorage.org/webt/pn/jr/qy/pnjrqyetbeyvoqxtnx715ge3s5w.png)
Please fix

**Comment by oleg-nenashev** [comment]
Thanks for catching it @gecube!

**Comment by amolmote** [comment]
Please close this issue as it is already solved

**Comment by DavidPHirsch** [comment]
stale
