### ISSUE TITLE
Add broken links check to the website CI

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/keptn.github.io#993]
Currently the CI does not check for broken links. It leads to issues like #991 which could have been easily prevented. There are GitHub Actions for that that could be enabled for the website:

* https://github.com/marketplace/actions/hugo-broken-link-check
* https://github.com/marketplace/actions/broken-link-check
* etc.

I recommend enabling Hugo Broken Link Check

**Comment by verma-kunal** [comment]
Hey @oleg-nenashev , i am interested to take up this issue! 
I am a beginner in the keptn community & some guidance would really help 🙂

**Comment by verma-kunal** [comment]
From what i understand is, we have to create a github action that would act as a check for broken link (if any), right?
